### ISSUE TITLE
[스터디 방향 회의] 스터디 계획 세우기

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#1]
- 일시: 2022-12-29 (목) 20시 ~ 22시 (2h)
- 장소: 디스코드 채널 라운지
- 내용: 스터디 방향 정하고 앞으로 계획과 목표 설정

**Comment by ParkJungYoon** [comment]
### ✔️ 스터디 내용 의견 수립

- 주디: CS스터디
- 팬시: CS공부 리뷰/코딩테스트 코드 리뷰/개인 프로젝트 리뷰
- 상혁: CS + 코딩테스트
- 현철: 우선순위 1. CS, 코테 위주의 공부 / 우선순위 2. 프로젝트 가능하다면 프로젝트 
- 은선: 1. Cs  2. 코테  3. 프로젝트를 통한 스프링공부 
- 네오: 코테 리뷰 / 팀 or 개별 프로젝트 / 스프링 학습
- 수연: 깃헙에 팀을 구성해서 그것에 스터디에서 한 것을 문서화하여 저장 / 개인프로젝트 코드 리뷰 / 책 리뷰 + 한단원씩 맡아서 설명후 질의응답 형식으로 진행 희망

### 📝 정리

- CS 5명/ 프로젝트 5명/ 스프링 학습 2명

**Comment by ParkJungYoon** [comment]
### 🤙 규칙

* 20시 03분부터 지각으로 간주
* 지각 3회시 결석 1회
* 결석 1회 시 벌칙
* 3회 연속 불참 시 벌칙
* 숙제 안 했을 때 벌칙
* 참석할 수 없을 경우 일요일 자정 전까지 불참 사유를 스터디원에게 공지

✔️ 벌칙의 구체적인 내용은 확정되지 않았음. (회식비를 받자는 의견 있었음)

**Comment by ParkJungYoon** [comment]
### 🎯 스터디 목표 수립

- 스터디 참고 도서: 면접을 위한 CS 전공지식 노트
  - 네트워크, 운영체제, 데이터베이스, 자료 구조 (2장~5장)
-  진행방식
  - 챕더마다 랜덤으로 두 팀으로 나눠 공부한 주제 발표 및 의견 나누기
  - 챕더가 끝나면 모든 스터디원이 모여 모의 CS면접 수행
 
공부한 내용을 입 밖으로 꺼내보는게 중요하다고 생각합니다! 공부한 내용을 서로 설명하며 죽은 지식이 아닌 살아있는 지식을 바꾸고자 합니다.
또한 공부하며 놓친 내용을 습득하는 목적도 가집니다.

최종적으로 공동 학습으로 자신이 가진 지식을 면접에서 잘 설명할 수 있는 개발자가 되고자 합니다.

**Comment by ParkJungYoon** [comment]
아...제목부터 내용까지..이게 아니었는데......마음에 안들어요 ㅠ_ㅜ 내 이슈들 날린 팬시... 가만안둬.....(?) 
생각날 때마다...수정하는걸루...

**Comment by jthugg** [comment]
디렉토리, 파일 명명 규칙

영문만 허용 단어 사이 언더스코어(_), 각 단어 첫글자는 대문자.

해당 문서를 다시 봤을 때, 추가적인 검색의 비용이 들지 않도록 자세히 기록한다.

**Comment by devFancy** [comment]
## 👐 컨벤션

### 작성 방법

* 폴더와 파일명은 모두 영문 소문자로 작성한다.(공백은 '_'으로 채운다)

* 맨앞에 category를 포함해서 작성한다.

* 예) CPU 스케줄링 알고리즘 -> os_cpu_scheduling_and_algorithm.md

* 해당 문서를 다시 봤을 때, 추가적인 검색의 비용이 들지 않도록 쉽고 단순하게 작성한다.

* 제목이 길어져도 이해를 우선시하여 작성한다.

### 커밋 Convention

``` markdown
파일 생성 시 docs: [카테고리] md 파일 명
이미지 파일 업로드 시 add: [카테고리] 커밋 메시지
파일 내부 수정 시 chore: [카테고리] 커밋 메시지
파일명 수정 시 rename: [카테고리] 커밋 메시지
오류 처리시 fix: [카테고리] 커밋 메시지

CPU 스케줄링 알고리즘
예) docs: [OS] CPU 스케줄링 알고리즘
예) add: [OS] 파일 추가
예) chore: [OS] 내용 추가
예) rename: [OS] 이름 수정
예) fix: [OS] 오류 처리
```

## Reference
[2023-CS-Study - README.md](https://github.com/Fancy96/2023-CS-Study)

**Comment by devFancy** [comment]
### Image file 가져오는 방법

예) img 폴더에 있는 png file -> md

* md file name : os_segmentation.md

* png file name : os_16_segmentation_1.png

* os_segmentation.md에서 `![](/OS/img/os_16_segmentation_1.png)` 를 입력하면 해당 png file 를 가져올 수 있다.
