### ISSUE TITLE
[전체] KPT 회고(Retrospection) : 1차 목표 달성 🎉

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#109]
## 💭 KPT 회고(Retrospection)
- `일시`: 2023-03-16 (목) 22시~22시반 (30m)
- `참석자`
  - 7명 (팬시, 주디, 네오, 상혁, 현철, 수연, 은선)
- `내용`: KPT 회고

### KPT (KEEP-PROBLEM-TRY) 방식
 
KPT는 애자일 운동의 창시자 중 한 명으로 알려진 미국의 프로그래머 알리스테어 콕크번에 의해 제안된 방법론입니다. 애자일이 전체적으로 프로젝트를 운영하는 방법론이라면, KPT는 프로젝트의 진행 단계에서 세부적인 액션을 시각적으로 분류하여 효과적으로 회고하고, 모든 구성원의 숙고가 반영된 개선안을 도출할 수 있는 방식입니다.

```
KEEP : 좋았던 부분, 앞으로 계속 유지하고 싶은 방식
PROBLEM : 잘 되지 않았던 부분, 문제라고 생각하는 부분
TRY : PROBLEM을 해결할 수 있도록 실천해보고 싶은 솔루션
```

진행 방식에 대한 자세한 설명은 '[실수와 문제가 없는 스타트업은 없다](https://brunch.co.kr/@fromjayden/8)' 해당 글을 참고해주세요.

---

우리 22년 11월에 처음 만났는데~ 벌써 23년 3월이야~

모두 고생했어요!!
초반에 계획한 네트워크, 운영체제, 데이터베이스, 자료구조를 끝내는 날이네요.
아직도 공부해야할 것들이 많아요. 개발자는 평생 공부해야됩니다. 후후후
1회독한 기본 과목들은 이제 계속 모의 면접으로 다져야겠죵?!

매 챕터마다 회고를 진행했지만, 다음 스터디 진행에 앞서 다 같이 이야기해보는 시간을 가지려고 해요.
#105  모의면접이 끝난 후 진행할 예정이고 Keep, Problem, Try 순으로 짧게 생각해서 작성할 시간을 가지고 함께 이야기하고 넘어가는 방식으로 진행할 거예요! 자세한 내용은 회고 때 안내하겠습니다! 안~뇽~

---

### 결정된 내용

1. 모의 면접 
  - 매주 화요일 팀별 기술 + 인성 면접
2. 과제
  - 이번 주: 누락된 파트 보충 (기존 방식과 동일하게 개인 주제 선정해서 PR, 발표 X)
  - 그 이후: 자바 분량 정해서 공부 (모의면접 질문에 포함,정리X, 발표X)
3. 벌금 : 3만원

**Comment by ParkJungYoon** [comment]
### KEEP (주디)

- 개념을 공부하는 시간을 가지고 모의 면접을 가져서 좋았습니다.
- 모의 면접에서 꼬리의 꼬리를 무는 질문을 할 수 있었던 이유는 개념 공부를 했기 때문이라 생각해요! 질문을 하기 위해선 해당 개념을 저또한 숙지를 해야하기 때문에 질문자, 답변자 모두 공부할 수 있었다고 생각합니다.
- 모두 정리를 열심히 해주셔서 공부할 때 많은 도움이 됐어요!

**Comment by BHC-Chicken** [comment]
### KEEP (hash)
 - 매주 각자가 정한 부분을 공부하고 발표하는 방식이 좋았습니다.
 - 꼬리 질문으로 계속 깊게 파고 들어가는 것이 좋았습니다.

**Comment by jthugg** [comment]
### KEEP (네오)

- 매 주 각자 공부한 자료를 모으고 챕터별 모의면접을 진행하는점이 좋았습니다.
- 모의 면접으로 공부한 파트를 각인 시킬 수 있는점이 공부하는데 많은 도움이 됐습니다!

**Comment by baekeunsun** [comment]
### KEEP(은선)
- 다양한 관점에서 질문을 받을 수 있어서 좋았습니다.
- 혼자서 글을 읽기만 하는 공부 방식이 아닌, 한 주마다 그 챕터의 준전문가(?)가 되어 설명해주신 덕분에 더 빠르고 잘 이해할 수 있었습니다.

**Comment by devFancy** [comment]
### KEEP(팬시)
- 좋았던 부분 : 체계적으로 진행되는 점(**스터디 진행 과정 / Issue, PR 형식**)이 매우 만족하고 구성원들 전부 열심히 하셔서 제가 더 잘해야겠다는 반성이 드네요..ㅎㅎ😅
- 앞으로 계속 유지하고 싶은 방식 : 한 챕터의 **주제에 대해 정리하는 방식**이 깔끔해서 계속 진행해도 괜찮을 것 같습니다.

**Comment by namtndus** [comment]
### KEEP (수연)
- 정리를 하고, 그 내용을 설명하는 방식이 다른 사람의 내용을 이해하는 것에 도움이 되었어요
- 모의 면접을 통해 더 깊게 배우는 방법을 알아가서 좋았습니다
👍

**Comment by sanghyuk2** [comment]
### KEEP(상혁) 

- 장점과 단점 둘 다 가지고 있는 부분이지만, 고수하고 싶은 방식은 챕터별로 포스팅을 올리는 것입니다. 
- 단순 암기식으로 책을 보고 이해를 하더라도 인간은 망각의 동물이기에 일정 시간이 지나면 까먹는다고 생각합니다. 
- 이에 포스팅을 통한 방식으로 기록된 자료를 통해 이해했던 지식들을 상기할수 있는 좋은 방식이라고 생각합니다. 
- 하지만 각 챕터별로 한 명씩 준비를 해오기 때문에, 자기가 준비하는 지식 외에는 소홀한 부분이 생겼던 것 같아(개인적으로) 단점도 존재한다고 생각합니다.

**Comment by BHC-Chicken** [comment]
### PROBLEM (hash)
 - 매주 조금씩 규칙이 바뀌어서 헷갈릴 때가 있습니다.

**Comment by devFancy** [comment]
### PROBLEM(팬시)

* 모의 면접을 진행하면서 정리하는 방식과 그것을 개선하는 점이 약간 부족한 것 같습니다.
* 7명으로 진행되어서 다양한 면접질문을 들을 순 있으나, 그것을 전부 커버하는 점이 오히려 독이 될 수 있다고 생각합니다. 

* 애자일 방식으로 진행하면서 조금씩 개선해가는 점은 좋으나, 피로도 같이 쌓이는 점이 있습니다.

**Comment by ParkJungYoon** [comment]
### PROBLEM (주디)

- 초반에 규칙을 정하긴 했지만 뒤로 갈수록 지켜지지 못했던 거 같아요.
- 첫 번째로 과제 PR 제출 기한을 스터디 전날 자정으로 정했지만 12시까지 올려주시는 분이 많지 않았던 거 같습니다! 추가 커밋을 허용하기로 했으니 이 부분은 지켜졌으면 좋겠어요.
- 두 번째로 시간 약속이에요! (지난 일요일..정윤박)

**Comment by jthugg** [comment]
### PROBLEM (네오)

- 챕터별로 각자 맡은 파트의 자료를 정리하는과정 중에 누락된 챕터도 있고 누락된 파트의 보충 없이 챕터를 마무리하게되는 점이 아쉬웠습니다.
- 가능하다면 키워드로 정리된 파트들을 다 채우고 나서 다음 챕터로 넘어가야하지 않나 라는 의문이 들었습니다.

**Comment by baekeunsun** [comment]
### PROBLEM(은선)
- 자신이 맡은 파트가 아니면, 지식이 비교적 빨리 휘발되는 것 같습니다.
- 줄글로 개념만을 작성해왔을 경우, 그 발표 팀이 아니면 인터넷 검색을 통해 아는 것과 차이가 없다고 느껴졌습니다.
- 너무 세세하게 파고드는 경향이 있다고 생각했습니다.

**Comment by namtndus** [comment]
### PROBLEM (수연)
- 약속시간이 조금씩 미루어지는 것
- 마감 시간을 지키지 않은 것 (feat 그게 나야! 뚬바뚬바 뚜비뚜바)

**Comment by sanghyuk2** [comment]
### PROBLEM(상혁)

- 앞서 **KEEP** 부분에서도 언급했던 부분이지만, 개인적으로 각각 자신이 준비해야했던 챕터가 특정되어 있기에, 그에 집중하느라 다른 사람들이 준비한 챕터를 공부하는 시간이 부족했습니다. 
- 자신이 맡은 주제는 깊이 공부할 수 있다는 장점도 분명히 존재하지만, 다른 사람의 주제의 경우 저의 경우 제가 맡은 챕터에 비해 공부하는 시간이 상대적으로 부족하여 시간이 지났을 때 기억이 삭제(?) 되는 경우가 즐비하여 아쉬웠습니다.

**Comment by BHC-Chicken** [comment]
### TRY (hash)
 - 벌금 5만원
 - 담주부터는 누락파트 보충이 좋다고 생각합니다.
 - 자바 스터디를 한다면 한 지금 스터디 방식처럼 챕터별로 공부하고 각자 발표하는게 좋다고 생각합니다.

**Comment by sanghyuk2** [comment]
### TRY(상혁)
- 자바 진행 방식 : 여럿이서 같은 챕터 공부
- CS 면접 팀 나누는 것 : 찬성
- 벌금 : 5만원

**Comment by devFancy** [comment]
### TRY(팬시)

* 자바 스터디 : 여럿이서 같은 챕터를 공부한다. (챕터 갯수는 매주 회의때 결정)

* 모의면접은 7명이 아닌 2/2/3 또는 3/4으로 진행하면, 개인이 받을 수 있는 질문이 많아지고 질적으로 좋아질 것 같습니다.

* 벌금은 3-5만원 / 불가피한 사유는 벌금에서 제외한다.

* 보충부분에 대해 OS/Network/DB/Algorithm 전체적으로 다음주(1주일)에 진행하면서, 각자 1가지 파트를 맡아 정리하지 못한 파트를 채우는 기간으로 하면 좋을 것 같습니다. (현재 6-7개 정도 있네요)

* 스터디 진행외에 깃허브 관리측면에서 개별적으로 업무(주/부)를 맡았으면 좋겠습니다.

**Comment by ParkJungYoon** [comment]
### TRY (주디)

- 앞으로 진행 방향
  -  공부
     - 자바 : 공통 범위를 정해서 학습
     - 누락 파트 : 각자 주제 정해서 기존과 동일하게 PR
 - 모의 면접 (주1)
    - 여러 팀으로 나눠서 인성면접과 동일한 방식으로 전 범위 CS 면접
 - 인성 면접 (주1)
 
- 벌금 : 3만원

**Comment by baekeunsun** [comment]
### TRY(은선)
1. 자바 진행 방식 + 누락파트 보충
- 화 : 자바 개념 각자 정리, 누락파트 PR / 목 : 인적성 + 기술 면접 (요일은 예시입니다)
2. CS 면접 팀나누기
- 찬성, 고정된 팀원으로 가는 게 아닌 매주 바뀐다면 팀 나누는 것이 더 효율적일 것 같습니다.
3. 벌금
- 3만원 ㅠ_ㅠ

**Comment by namtndus** [comment]
### TRY (수연)
- 벌금은 5만원 좋습니다 
- 자바 공부는 지금처럼 공부하는 것을 정리해서 올리는 방식이 좋다고 생각합니다
- 매주 모의면접을 진행하는 것도 좋다고 생각합니다.
- 매주 자바스터디와 모의 면접 이 두 시간을 가지고 좋겠습니다.

**Comment by jthugg** [comment]
### TRY (네오)

- 자바 스터디 방향
    - 책을 통해 챕터별로 자료를 만들어 정리하는 방식이었으면 좋겠습니다.
    - 이미 얘기가 나와서 책을 따로 정하지 않고 스터디만 진행하는경우 모의면접 내용이 모호해질 수 있다고 생각합니다.
- 벌금 관련
    - 5만원 고!
    - 전후 사정이 애매한 경우 듣고 벌금 부과가 적절한지 투표과정 진행
- 면접 팀 나누기
    - 모의면접또한 공부 주간 처럼 팀을 나눠서 더 많은 질문들을 공유 할 수 있었으면 좋겠습니다.
- 누락된 파트 보충
    - 용어 정리 
        - 챕터: 예) 네트워크, 디비 등...
        - 파트: 예) 레드블랙트리, HTTP 발전 과정 등...
    - 전체 챕터 중 누락 된 파트들을 정리해서 매 주 각자 정리 할 파트를 정하고 이제껏 진행 해왔던 방식대로 자료를 보충한다.
- 강의 영상 제작
    - 개인적인 의견이지만 직접 제작한 자료로 강의 영상을 제작해 배포하는것을 시도해봤으면 좋겠습니다.
    - 개인별로 일정이 빠듯 할 수 있지만 상호간에 글로 작성된 자료만 보고 공부하는것에는 한계가 있다고 생각합니다.
    - 이해를 위해 도움이 될 만한 영상을 제작해 유튜브 업로드 하는 시도를 해봤으면 좋겠습니다.
    - 공개 범위는 일부 공개 설정으로 링크를 리드미에 공개하는 방식이었으면 좋겠습니다.

**Comment by ParkJungYoon** [comment]
## 정리

1. 모의 면접 
  - 매주 화요일 팀별 기술 + 인성 면접
2. 과제
  - 이번 주: 누락된 파트 보충 (기존 방식과 동일하게 개인 주제 선정해서 PR, 발표 X)
  - 그 이후: 자바 분량 정해서 공부 (모의면접 질문에 포함,정리X, 발표X)
3. 벌금 : 3만원
