### ISSUE TITLE
[23년 3월 4주차] 모의 면접 + 보충 학습

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#110]
## 🚀 스터디

- `일시`: 2023-03-21 (화) 20시 ~ 22시 (2h)
  - 일정 변경은 적어도 전날까지. 불가피한 사정 외에 당일 변경 시 벌금(3만원)
- `참석자`
  - [x] 👨‍💻 A팀 (팬시, 네오, 상혁, 현철)
  - [x] 👩‍💻 B팀 (주디, 수연, 은선)
- `내용`
  -  팀별 인성 + 기술 모의면접 
  - `범위` : 지금까지 공부한 전범위 (이번주 보충 과제는 범위에 포함하지 않습니다.)
  - `면접 내용 기록` : notion
  - `진행 방식` : 팀별 모의면접, 모르는 질문은 과감하게 패스! 그리고 밑줄 그어두고 그 다음 주에 다시 질문받기!
- 정해야할 것
  - [x] 다음 면접 팀 정하기
  - [x] 자바 공부 범위 정하기  

### 🧩 과제
1. **보충 주제** : 아래 보충 주제 중 한 가지를 선택하고 정리한 뒤 PR 제출합니다. 해당 내용은 따로 발표하지 않습니다.
```
🚀 자료 보충 목차

2. 네트워크
- [x] OSI 7계층
- [x] HTTPS

4. 데이터베이스
- [x] 스키마

5. 자료구조 & 알고리즘
- [x] 그래프
- [x] 이진탐색
- [x] 완전탐색
- [x] 그리디 알고리즘
```
- `PR 마감 날짜`: 월요일 자정
  - 지각 시 벌금(3만원)
2. **면접 준비**
- 모의면접을 위해 부족했던 부분을 학습합니다.
- `가이드라인` : 짧은 시간 안에 모든 주제를 다 습득하는 건 어렵다고 생각해요. 그래서 각자 목표를 “나는 이번 주에는 네트워크는 어느정도 다 숙지하겠어!” “나는 운영체제 가상메모리가 아직 부족하니깐 이 부분을 더 공부하겠어!”라고 목표를 세워서 준비했으면 해요! 모의면접 때 대답못해도 좌절하지마요! 다음 주에 그 부분을 채우면 돼요!

**Comment by ParkJungYoon** [comment]
오늘 이야기 나누면서 여러가지가 많이 바뀌어서 헷갈릴 수도 있을거 같아요!!! 
일단 이번 주는 이슈 토대로 준비하시면 됩니다!!!

과제할 주제 똑같이 댓글 남겨주시면 되고 다음주부터는 소수로 면접 진행하니깐 덜 힘들거예요..! 하하하하ㅏㅎ ㅠㅠㅠ 미안합니다ㅠㅠ 이제는 길게 안해요(?) 스피디해요 휙휙휙 하팅!!!

**Comment by ParkJungYoon** [comment]
정윤!! `HTTPS` 가쥬아

**Comment by baekeunsun** [comment]
`그리디 알고리즘` 하겠습니다!


앞으로의 방향을 정하다보니 피치 못하게 길어진거라고 생각해요.
주디도 오늘 여러모로 피곤했을텐데, 열정적으로 스터디 주도해줘서 고마워요😊💗

그치만 3시간 반 쉽지않네요😅 기절각..
다들 너무 수고 많으셨습니다! 화요일에 뵈어요

**Comment by jthugg** [comment]
`OSI 7계층` 하겠습니다!

다들 고생하셨습니다!!

**Comment by namtndus** [comment]
`스키마` 하겠습니다! 다들 고생하셨습니다.

**Comment by devFancy** [comment]
저는 `그래프` 하겠습니다.

**Comment by sanghyuk2** [comment]
`이진탐색` 준배해오겠습니다.

**Comment by BHC-Chicken** [comment]
`완전탐색` 준비해오겠습니다.
