### ISSUE TITLE
[23년 3월 5주차] 모의 면접 + Java 공부

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#121]
## 🚀 스터디

- `일시`: 2023-03-28 (화) 20시 ~ 22시 (2h)
  - 일정 변경은 적어도 전날까지. 불가피한 사정 외에 당일 변경 시 벌금(3만원)
- `참석자`
  - [x] 👨‍💻 A팀 (상혁, 네오, 주디, 수연) -> 30일 (목) 20시
  - [x] 👩‍💻 B팀 (은선, 팬시, 해쉬)
- `내용`
  -  팀별 인성 + 기술 모의면접 
  - `범위` : 지금까지 공부한 전범위 + 저번주 보충 과제 + Java 과제
  - `면접 내용 기록` : notion
  - `진행 방식` : 팀별 모의면접, 모르는 질문은 과감하게 패스! 그리고 밑줄 그어두고 그 다음 주에 다시 질문받기!
- 정해야할 것
  - [x] 다음 면접 팀 정하기
  - [ ] 프로젝트 관련 내용 회의
  - [x] 회식 날짜 정하기

### 🧩 과제
1. **자바 공부** 
  - [x] `공통`: 아래 리스트에 있는 주제 공부해오기
  - [x] `선택1`: 아래 주제 중 한 가지를 선택하고 정리한 뒤 PR 제출합니다. 해당 내용은 따로 발표하지 않습니다.
  - [x] `선택2`: 어떤 방식이든 본인이 공부한 증거를 아래 코멘트를 남깁니다.
```
- 객체지향(상속, 다형성, 캡슐화 등)
- JVM 메모리 구조
- 컴파일 과정
- 다양한 GC(parellel, g1gc 등)
- JRE, JDK, JVM의 구분
- 자바 메모리관리(Xms, Xmx)
- Call by Value vs Call by Reference
- String Immutable(String constant pool, "a" vs new String("a"))
- Auto Boxing & UnBoxing
- Error vs Exception
- Checked vs UnChecked Exception
- 비동기처리 문법 비교
```
- [리스트 출처](https://appleg1226.tistory.com/37)
- `과제 제출 마감 날짜`: 월요일 자정
  - 2가지 중 한가지 방법을 선택하고 월요일 자정까지 제출합니다. 
  - 지각 시 벌금(3만원)
2. **면접 준비**
- 모의면접을 위해 부족했던 부분을 학습합니다.
3. **프로젝트 회의 준비**
- 프로젝트 참여 여부
- (참여한다면) 프로젝트 팀 나누는 방식 (다같이 or 나눠서)
- (참여한다면) 프로젝트 주제
- (참여한다면) 프로젝트 기간

**Comment by ParkJungYoon** [comment]
## 일정 공지

28일과 29일에 저와 네오가 일정이 생겨 A팀만 스터디 날짜를 변경합니다!

 👨‍💻 A팀  (상혁, 네오, 주디, 수연 : **30일 (목) 20시**
 👩‍💻 B팀 (은선, 팬시, 해쉬) : **28일 (화) 20시**
 
 일정 잘확인하시고 스터디 모임 가집시다!! 
 그리고 프로젝트 관련 회의는 따로 날짜를 잡아서 이야기하는걸로 합시다!

**Comment by ParkJungYoon** [comment]
## 주디 과제 제출!

<img src="https://user-images.githubusercontent.com/97580782/227779033-55ddd679-6e50-4844-9d41-a360d7ab12e5.png" width = 150px>
<img src="https://user-images.githubusercontent.com/97580782/227779081-ede41e98-6ca5-4757-a47d-794b76078009.png" width = 450px>

**Comment by baekeunsun** [comment]
자바의`컴파일 과정`에 대해서 공부했습니다!
Java 폴더가 따로 없어서 혹여 다른 분들과 경로가 엇갈릴까봐 블로그에 포스팅했습니다.
한 주도 수고많으셨어요~😣💪

[[Java] 자바의 컴파일 과정](https://eunsun-zizone-zzang.tistory.com/74)

**Comment by BHC-Chicken** [comment]
GC에 대해서 공부했습니다. Notion에 작성하였습니다.
![스크린샷 2023-03-27 오후 9 30 17](https://user-images.githubusercontent.com/57649545/227941778-32698450-a703-487c-8fe8-1cb442cc2460.png)

**Comment by jthugg** [comment]
`객체 지향 프로그래밍`
`메모리 구조`
`컴파일 과정`
`클래스 로더`
`실행 엔진`
정리했습니다.

https://velog.io/@jthugg/series/java-study

**Comment by namtndus** [comment]
저는 객체지향에 대해서 공부 했습니다

https://windy-gruyere-1c9.notion.site/f969e8d5ddd64e7fb751b55571e8de0c

**Comment by ParkJungYoon** [comment]
와!! 다들 정리 정말 열심히 하셨네요!! 고생했습니다!!
서류 바쁜 시기 지나면 자바도 md 파일 모아용!!! 
주제 발표 시간도 되살리고 싶당!!! (나중에 여유생기면(?))

**Comment by sanghyuk2** [comment]
`Error와 Exception`에 대해서 정리했습니다.
![image](https://user-images.githubusercontent.com/41242710/227980728-bc432d8b-245d-4620-b7f7-1ac6503853a5.png)
