### ISSUE TITLE
[23년 4월 2주차] 모의 면접 + Java 공부

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#128]
## 🚀 스터디

- `일시`: 2023-04-14 (금) 20시 ~ 22시 (2h)
  - 일정 변경은 적어도 전날까지. 불가피한 사정 외에 당일 변경 시 벌금(3만원)
- `참석자`
  - [x] 👨‍💻 A팀 (네오, 은선, 수연, 상혁)
  - [x] 👩‍💻 B팀 (주디, 해시, 팬시)
  - 은선, 상혁 건강상 문제로 미참석
  - 팬시 개인 사정
- `내용`
  -  팀별 인성 + 기술 모의면접 
  - `범위` : 지금까지 공부한 전범위 + Java 과제
  - `면접 내용 기록` : notion
  - `진행 방식` : 팀별 모의면접, 모르는 질문은 과감하게 패스! 그리고 밑줄 그어두고 그 다음 주에 다시 질문받기!
- 정해야할 것
  - [ ] 다음 면접 팀 정하기

### 🧩 과제
1. **자바 공부** 
  - [x] `공통`: 아래 리스트에 있는 주제 공부해오기
  - [x] `선택1`: 아래 주제 중 한 가지를 선택하고 정리한 뒤 PR 제출합니다. 해당 내용은 따로 발표하지 않습니다.
  - [x] `선택2`: 어떤 방식이든 본인이 공부한 증거를 아래 코멘트를 남깁니다.
```
- Java 8의 특징
- Lambda(+ Functional Interface)
- Stream API
- Default Method
- Generic
- Reflection(Annotation)
- Collection Framework(List, Map, Set 등) 
- HashMap(https://d2.naver.com/helloworld/831311)
- Abstract Class vs Interface(default method)
- CountDownLatch & CyclicBarrier
```
- [리스트 출처](https://appleg1226.tistory.com/37)
- `과제 제출 마감 날짜`: 월요일 자정
  - 2가지 중 한가지 방법을 선택하고 월요일 자정까지 제출합니다. 
  - 지각 시 벌금(3만원)
 
2. **면접 준비**
- 모의면접을 위해 부족했던 부분을 학습합니다.

**Comment by sanghyuk2** [comment]
`Lambda(+ Functional Interface)` 에 대해 준비했습니다.

![image](https://user-images.githubusercontent.com/41242710/230780672-2a56624a-97dc-4da2-8df8-455f3a5ed01b.png)

**Comment by BHC-Chicken** [comment]
`Stream API` 공부했습니다.
![스크린샷 2023-04-10 오후 4 43 35](https://user-images.githubusercontent.com/57649545/230853265-18120775-5762-4a23-ac93-9caf2e32c92b.png)

**Comment by ParkJungYoon** [comment]
오홍! 저도 람다식과 스트림 API 학습했습니다.
다시 보니 늘 새롭네요(?)

<img src="https://user-images.githubusercontent.com/97580782/230877477-90c6ff96-691b-4919-991c-a7d4a16f1749.png" width = "450px">

**Comment by baekeunsun** [comment]
[[Java] Stream API](https://eunsun-zizone-zzang.tistory.com/84)
![image](https://user-images.githubusercontent.com/72916415/230899300-2f591d95-39b6-4ea5-938b-629f513c9a80.png)

`Stream API` 공부했습니다!
다들 짧은 방학(?) 잘 보내셨나요😋 
저는 시간 가는 줄 몰랐습니다,, 노는게 제일 조아 
금요일에 뵈어용

**Comment by devFancy** [comment]
저는 Java 8의 특징에 대해서 공부해봤습니다.

<img width="434" alt="스크린샷 2023-04-10 오후 11 00 13" src="https://user-images.githubusercontent.com/83820185/230916255-d75c8987-551b-4cb2-9777-5b18214ca0b4.png">

Reference 자료는 **모던 자바 인 액션**이라는 책입니다.

**Comment by namtndus** [comment]
자바 default method 에 대해 공부했습니다
![image](https://user-images.githubusercontent.com/53739820/230927026-63c6d084-0867-472c-8a20-60736ac1af86.png)

**Comment by jthugg** [comment]
늦어서 죄송합니다.. 😵‍💫
**디폴트 메서드** 공부해왔고 레퍼런스는 **자바의 정석** 기초편, **이것이 자바다** 최신 개정판입니다.

![Screenshot 2023-04-11 at 10 12 36 AM](https://user-images.githubusercontent.com/116662930/231030281-680c7863-48bb-4343-a440-39e0557d7e30.png)
