### ISSUE TITLE
[2장 네트워크 - 2] 2.3 ~ 2.5까지 내용 학습 및 선택한 주제 공부 

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#14]
### 🚀 스터디

- 일시: 2023-01-10 (화) 20시 ~ 22시 (2h)
- PR 마감 날짜: 스터디 전
- 참석자
  - [x] 상혁, 수연, 정윤, 은선, 현철, 준태
  - [x] sick ㅠㅠ 팬시

### 🎯 공통 주제

- 2.3 네트워크 기기
- 2.4 IP 주소
- 2.5 HTTP

이 부분은 각자 개인 공부로 진행하시면 됩니다.

### ✔️ To Do

- [x] 스터디 전까지 개인이 정리한 것을 PR 보내기, merge는 스터디 모임 때(이 내용을 토대로 발표)
- [x] 면접 준비(아직 학습 단계이기 때문에 서로 의견 나눌 수 있는 정도로만 준비하시면 됩니다)

**Comment by ParkJungYoon** [comment]
Network 리드미에 있는 목차 주제 중에서 선택하시면 됩니다! 만약 여러 주제를 묶어서 정리하고 공부하셔도 좋습니다!
추가적으로 떠오르는 주제 있다면 목차에 추가해주시면 됩니당!
한 주도 화이팅!!

**Comment by ParkJungYoon** [comment]
헤헤... 내가 일등으로 찜 해야지 
저는 2주차 주제로 `HTTP 진화과정` 준비해오겠습니당!

**Comment by devFancy** [comment]
저는 `SOP와 CORS` 준비해오겠습니다~

**Comment by sanghyuk2** [comment]
`REST API + RESTful` 준비하겠습니다

**Comment by namtndus** [comment]
저는 `쿠키와 세션` 준비하겠습니다.

**Comment by baekeunsun** [comment]
`프록시` 준비 하겠습니다!

**Comment by BHC-Chicken** [comment]
`네트워크 기기` 준비하겠습니다.

**Comment by jthugg** [comment]
`L7, L4 스위치 + 로드밸런싱` 준비 하겠습니다.
