### ISSUE TITLE
[Spring] 스프링 MVC 시작

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#163]
### 📚 챕터 구성
```
1. 웹 애플리케이션 이해
2. 서블릿
3. 서블릿, JSP, MVC 패턴
4. MVC 프레임워크 만들기
5. 스프링 MVC - 구조 이해
6. 스프링 MVC - 기본 기능
7. 스프링 MVC  - 웹 페이지 만들기
```

#### 1주차: 섹션1~3
- `담당자`: 은선
- `어시스턴트`: 네오

#### 2주차: 섹션4~5
- `담당자`: 해시
- `어시스턴트`: 수연

#### 3주차: 섹션6~7
- `담당자`: 주디
- `어시스턴트`: 팬시

### 💁‍♀️ 스터디 방식

- `모두`: 동일한 섹션(정해진 분량만큼)을 공부합니다. 그리고 공부한 내역을 이슈 코멘트에 남깁니다.
- `담당자`: 공부한 내용을 대표로 기록하고 PR을 올립니다.
- `어시스턴트`: 담당자를 도와 내용을 함께 정리합니다.
- `담당자`, `어시스턴트`: 담당자와 어시스턴트 중 기록물의 이해도가 높은 사람이 발표를 진행합니다.

**Comment by devFancy** [comment]
정리 하나는 `주디`가 짱이네요..! 👍👍
매번 정리하느라 감사합니다!!

**Comment by ParkJungYoon** [comment]
정리하는거 넘 좋아요 🤩
팬시도 오늘 자바 목록 정리해주셔서 감사합니다!! 👍👍
