### ISSUE TITLE
[23년 6월 1주차] Spring 공부

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#170]
## 🚀 스터디

스터디 날짜는 금요일이라서 목요일까지 PR 필수 ><

- `일시`: 2023-06-02 (금) 21시 ~ 23시 (2h)
  - 일정 변경은 적어도 전날까지. 불가피한 사정 외에 당일 변경 시 벌금(3만원)
- `참석자`
  - 상혁, 주디, 네오, 현철, 수연
  - `은선` : 개인 일정으로 불참
- `내용`
  -  개인 주제를 공부하고 정리해서 스터디 시간에 발표합니다!
- 해야할 것
  - [x] git organization 만들어서 이사가기

### 🧩 과제

1. **스프링 공부** 
  - [x] 공부하고 발표하고 싶은 주제를 정해 이슈 답글을 달아주세요!

```
- PSA, IoC, AOP, POJO(각각에 대한 내용과 도입 이유)
- Bean(Scope)
- ViewResolver
- Converter, Formatter
- Filter, Interceptor
- @Autowired 주입 방법별 차이(Field, Setter, Constructor Injection)
- ApplicationContext
- Web MVC 요청 처리 과정(DispatcherServlet을 중심으로)
- Spring vs Spring Boot
- @SpringBootApplication의 내부 구성
- @Controller vs @RestController
- Spring Security의 요청 처리 과정
```

- [리스트 출처](https://appleg1226.tistory.com/37)
- `과제 제출 마감 날짜`: 목요일 자정
  - 지각 시 벌금(3만원)

**Comment by BHC-Chicken** [comment]
`Filter, Interceptor` 준비하겠습니다

**Comment by sanghyuk2** [comment]
`@Autowired 주입 방법별 차이(Field, Setter, Constructor Injection)` 하겠슴다

**Comment by namtndus** [comment]
`PSA, IoC, AOP, POJO(각각에 대한 내용과 도입 이유)` 하겠습니다

**Comment by jthugg** [comment]
`Bean(Scope)` 하겠습니다~!

**Comment by ParkJungYoon** [comment]
`Bean Validation` 준비해올게용! 어우 주제 정하는데 반나절 걸렸어요 ㅎㅅㅎ

**Comment by ParkJungYoon** [comment]
아니다... spring security..? 아 너무 방대한 파트라서 고민되는데.. 쓰읍... 오늘 제가 뭘 정리할지는... 랜덤입니다(?)
