### ISSUE TITLE
[23년 6월 2주차] Spring 공부

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#179]
## 🚀 스터디

스터디 날짜는 금요일이라서 목요일까지 PR 필수 ><

- `일시`: 2023-06-09 (금) 21시 ~ 23시 (2h)
  - 일정 변경은 적어도 전날까지. 불가피한 사정 외에 당일 변경 시 벌금(3만원)
- `참석자`
  - 은선, 주디, 네오, 현철, 상혁, 수연
- `내용`
  -  개인 주제를 공부하고 정리해서 스터디 시간에 발표합니다!
- 해야할 것
  - [x]  다음 주제 정하기, 아마 JPA?!

### 🧩 과제

1. **스프링 공부** 
  - [x] 공부하고 발표하고 싶은 주제를 정해 이슈 답글을 달아주세요!

```
- ViewResolver
- Converter, Formatter
- ApplicationContext
- Web MVC 요청 처리 과정(DispatcherServlet을 중심으로)
- Spring vs Spring Boot
- @SpringBootApplication의 내부 구성
- @Controller vs @RestController
```

- [리스트 출처](https://appleg1226.tistory.com/37)
- `과제 제출 마감 날짜`: 목요일 자정
  - 지각 시 벌금(3만원)

**Comment by sanghyuk2** [comment]
`Web MVC 요청 처리 과정(DispatcherServlet을 중심으로)` 담당하겠습니다 :-)

**Comment by namtndus** [comment]
`ViewResolver`하겠습니다! 상혁님 빠르시네요 ㅎㅎ

**Comment by ParkJungYoon** [comment]
ㅃ...빠르다..! ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by sanghyuk2** [comment]
작성하고 뻗었습니다 ㅋㅋㅋㅋ

**Comment by jthugg** [comment]
`@Controller vs @RestController` 하겠습니당 \~.\~

**Comment by BHC-Chicken** [comment]
`Spring vs Spring Boot`하겠습니다.

**Comment by baekeunsun** [comment]
오랜만이에용~! `ApplicationContext` 하겠습니닷

**Comment by ParkJungYoon** [comment]
꺄~ 시간 너무 빨라용! 저는 `@Valid` 하겠습니당
