### ISSUE TITLE
[23년 7월 2주차] 운영체제 복습 - 1

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#198]
## 🚀 스터디

- `일시`: 2023-07-09 (일) 21시 ~ 23시 (2h)
  - 일정 변경은 적어도 전날까지. 불가피한 사정 외에 당일 변경 시 벌금(3만원)
- `참석자`
  - 은선, 주디, 네오, 현철, 수연
- `미참석자`
  - 상혁, 팬시
- `내용`
  -  운영체제 전체 서술형 퀴즈 타임.
- `To Do`
  - [x]  각자 맡은 파트 질문 노션 페이지에 작성하기
  - [x]  운영체제 전체 복습

### 🕵️ 각자 맡은 주제

```
1번(현철): 인터럽트, 시스템 콜
2번(수연): 운영체제와 컴퓨터
3번(팬시): 주소 공간과 가상 메모리(Address Space, Virtual Memory),  주소 변환(Address Translation)
4번(네오):  프로세스와 스레드
5번(주디): PCB와 Context Switching
6번(은선):  CPU 스케줄링 알고리즘
7번(상혁):  메모리 계층
```

![image](https://github.com/devSquad-study/2023-CS-Study/assets/97580782/abaf1e8e-10a9-4a1e-8ea9-54b98740787a)

### ✍️ 스터디 방식

- `스터디 전`

1. 자신의 주제를 확인한다.
2. 노션 페이지에 질문을 작성한다. (**미리 보기 금지!!!** 양심에 맡겨요!!!)

- 자신의 토클 밑에 질문란에 문제를 작성한다.

<img src="https://github.com/devSquad-study/2023-CS-Study/assets/97580782/de1afe8e-3d0a-41fd-b192-7aac93027f96" width=400>

<br>

- `스터디 중`

1. 각자 자신의 문제를 제외하고 토글을 복사해서 답변을 작성한다.

<img src="https://github.com/devSquad-study/2023-CS-Study/assets/97580782/46d19156-3b39-4468-8e2b-d830543d2e31" width=400>

2. 문제를 푼 다음 많은 사람들이 못 푼 문제는 출제자가 간단하게 설명한다.

**Comment by ParkJungYoon** [comment]
### 07.09(일) 주디

하놔... 뭔가... 풀긴 풀었는데 어렵네요.. 쓰읍
문제만 출제하고 사라진 팬시.. 매워요 창의력을 발휘해서 답변 적었습니다.
CS 문제에 창의력 발휘하는 사람
일단 46분까지 다시 고쳐볼게용

![image](https://github.com/devSquad-study/2023-CS-Study/assets/97580782/1d0463ad-692d-4972-916e-5d3ed7101e92)

**Comment by BHC-Chicken** [comment]
풀수 있는건 다 풀긴 했는데 찝찝하네요. 저도 46분까지 다시 고쳐 볼게요.

**Comment by baekeunsun** [comment]
## 은선 문제 다 풀었습니다🏍

나름 운영체제 열심히 본다고 봤는데 쉽지않네요 특히 팬시 파트,, 
취약한 파트는 계속 취약하네요 ㅠ 슬퍼

그래도 일단 빈칸은 안만드려고 기억을 다 꺼내서..뭐라도 죽이되든 밥이되든 적었습니다ㅋㅋㅋㅋㅋ 

이번주도 수고 많으셨어요 제발 커피값 멈춰..

<br>


![image](https://github.com/devSquad-study/2023-CS-Study/assets/72916415/d4219a1c-c2ff-4f7e-93d3-dc1a5402b4f3)

쉽게 낸다고 낸건데..?! 했으나 경쟁자 제거의 의미론 좋군요(?) 
다들 남은시간까지 파이팅입니다

**Comment by namtndus** [comment]
저도 기억을 짜내서 적기도 했고 소설을 하나 창작을 한 것 같아요...
팬시님 문제는 저에게 너무 어렵네요 ㅜㅜ

**Comment by ParkJungYoon** [comment]
### 결과

```
문제 배점 : 10점
총점 : 80점
과락 : 40점
8문제
```

빠르다..
현철님 비선점이기 때문에 우선순위 발생해서 인터럽트가 오더라도 시스템콜 열정만 불태우며 멈추지 않는다.. 머...멋지다.
(그리고 암살시도로 경쟁자 제거한 수연쓰..(?))

![image](https://github.com/devSquad-study/2023-CS-Study/assets/97580782/ee3b4525-e99e-4b8d-86c7-d2466c391403)
