### ISSUE TITLE
[23년 7월 3주차] 운영체제 복습 - 2

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#203]
## 🚀 스터디

- `일시`: 2023-07-16 (일) 21시 ~ 23시 (2h)
  - 일정 변경은 적어도 전날까지. 불가피한 사정 외에 당일 변경 시 벌금(3만원)
- `참석자`
  - 은선, 주디, 수연, 상혁
- `미참석`
  - 네오 : 개인 사정
  - 팬시 : 7월 불참 
  - 현철 : 기차 이슈
- `내용`
  -  운영체제 전체 서술형 퀴즈 타임.
- `To Do`
  - [x]  각자 맡은 파트 질문 노션 페이지에 작성하기
  - [x]  운영체제 전체 복습

### 🕵️ 각자 맡은 주제

```
1번(상혁): 세그먼테이션(Segmentation)
2번(주디):  페이징(Paging)
3번(네오): TLB(Translation Lookaside Buffers)
4번(현철): 프로세스, 스레드 (심화로 출제해주세요)
5번(팬시): 동기화(스핀락, 세마포어, 뮤텍스)
6번(수연): 교착상태(DeadLock)
7번(은선):  메모리 계층
```

![image](https://github.com/devSquad-study/2023-CS-Study/assets/97580782/abaf1e8e-10a9-4a1e-8ea9-54b98740787a)

### ✍️ 스터디 방식

- `스터디 전`

1. 자신의 주제를 확인한다.
2. 노션 페이지에 질문을 작성한다. (**미리 보기 금지!!!** 양심에 맡겨요!!!)

- 자신의 토클 밑에 질문란에 문제를 작성한다.

<img src="https://github.com/devSquad-study/2023-CS-Study/assets/97580782/de1afe8e-3d0a-41fd-b192-7aac93027f96" width=400>

<br>

- `스터디 중`

1. 각자 자신의 문제를 제외하고 토글을 복사해서 답변을 작성한다.

<img src="https://github.com/devSquad-study/2023-CS-Study/assets/97580782/46d19156-3b39-4468-8e2b-d830543d2e31" width=400>

2. 문제를 푼 다음 많은 사람들이 못 푼 문제는 출제자가 간단하게 설명한다.

**Comment by ParkJungYoon** [comment]
### 🐰 주디

겨...경쟁자가 줄고 있어!!! 안돼~

![image](https://github.com/devSquad-study/2023-CS-Study/assets/97580782/3b47424d-d683-47f3-88d5-c6506988e821)

**Comment by baekeunsun** [comment]
### 다 푼사람 저요🙋‍♀️🛬

딱 과락만큼만 문제풀었어요.,, 
다 맞아야지 통관데 제발제발 빌고있습니다ㅠ_ㅠ
뿌엥..

**Comment by ParkJungYoon** [comment]
드디어 나에게도 커피 쿠폰의 날이... 따흡 감동란
오늘 후기: 따봉 정처기

![image](https://github.com/devSquad-study/2023-CS-Study/assets/97580782/000f9b81-4e48-4754-8e9f-6c329c1d116f)
