### ISSUE TITLE
[23년 7월 5주차] 자바 복습 - 1

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#205]
## 🚀 스터디

후후 복습까지 완벽하게 하는 CS 스터디 짱 멋지다.

- `일시`: 2023-07-30 (일) 21시 ~ 23시 (2h)
  - 일정 변경은 적어도 전날까지. 불가피한 사정 외에 당일 변경 시 벌금(3만원)
- `참석자`
  - 은선, 주디, 수연, 상혁, 네오
- `불참`
  -  현철
- `내용`
  -  자바 서술형 퀴즈 타임.
- `To Do`
  - [x]  각자 맡은 파트 질문 노션 페이지에 작성하기
  - [x]  자바 전체 복습

### 🕵️ 각자 맡은 주제

```
1번(현철): JVM 메모리 구조 (2개)
2번(은선): Garbage Collection(GC) (2개)
3번(네오): 객체지향 (2개)
4번(상혁): Java version, Java 컴파일 과정
5번(수연): Call by Value vs Call by Reference, Mutable, Immutable
6번(정윤): 람다, 스트림 API
```
![image](https://github.com/devSquad-study/2023-CS-Study/assets/97580782/d1d924b8-453e-4186-9695-dc235758ee00)

### ✍️ 스터디 방식

- `스터디 전`

1. 자신의 주제를 확인한다.
2. 노션 페이지에 질문을 작성한다. (**미리 보기 금지!!!** 양심에 맡겨요!!!)

- 자신의 토클 밑에 질문란에 문제를 작성한다.

<img src="https://github.com/devSquad-study/2023-CS-Study/assets/97580782/de1afe8e-3d0a-41fd-b192-7aac93027f96" width=400>

<br>

- `스터디 중`

1. 각자 자신의 문제를 제외하고 토글을 복사해서 답변을 작성한다.

<img src="https://github.com/devSquad-study/2023-CS-Study/assets/97580782/46d19156-3b39-4468-8e2b-d830543d2e31" width=400>

2. 문제를 푼 다음 많은 사람들이 못 푼 문제는 출제자가 간단하게 설명한다.

**Comment by ParkJungYoon** [comment]
공동의 1위에 오른 정윤와 상혁.
과연 커피 쿠폰은 누가 획득할 것인가.

![9B70F400-57FD-40D5-8500-45DCECFA9B23](https://github.com/devSquad-study/2023-CS-Study/assets/97580782/44a41f5c-ed05-42f7-b2aa-71268d1bb0fb)

뭐야? 나?!!! 상혁 서잇가이가 네트워크 이슈인 척 봐준걸로><

![image](https://github.com/devSquad-study/2023-CS-Study/assets/97580782/8a47581d-a2f2-45cc-9eda-58ae648f8e09)

![image](https://github.com/devSquad-study/2023-CS-Study/assets/97580782/8cabb24d-3885-4fc8-896f-f3c7b7e0711e)

**Comment by sanghyuk2** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by ParkJungYoon** [comment]
### 네오가 공유해 준 자바 질문 참고자료

- [🕊️ 주니어 자바 개발자를 위한 100가지 질문 (1)](https://careerly.co.kr/comments/83898?utm_source=paid_facebook&utm_medium=webtraffic&utm_campaign=FB_UA_WebTraffic_Engineer_Test_Web&utm_content=Test_Comment_Mass_Information_ImageSlide_003&fbclid=PAAaYrhvIJxn-XrGZNsny-h_hgPt4TWCAOrgqSH0qE6rM7_YYAj-48qYUbq8M_aem_AdC5tRd-CjUen88EviT3ZttOePRNB3umXNLfc-DJSLy5BiQ1Yrs_wV6Scpy2IF6CXFG_ly6FG907W8fv_GOGyqzt)

**Comment by ParkJungYoon** [comment]
이번 주는 전원 합격!!!! 과락 아무도 없어용~ 멋져멋져
