### ISSUE TITLE
[23년 10월 3주차] 옵저버 패턴

### ISSUE THREAD

**Issue by baekeunsun** [Fancy96/2023-CS-study#217]
### 🚀 스터디

- `일시`: 2023-10-18 (수) 21시 ~ 22시 (1h)
- `참석자`
  - [x] 4명(네오, 은선, 수연, 현철)
      - 상혁 : 면접
- `내용` : 디자인 패턴 이론 공부, 그를 바탕으로 실습 진행

### ✍️ 스터디 방식

1. 책을 통해 이번 주 `디자인 패턴`을 공부한다.
2. 해당 패턴을 이용하여 `미션`을 푼다.
4. 스터디 `전날 12시` ~ `스터디 전` 까지 PR을 날린다.
5.  `코드 리뷰`는 `자율`!

### 🎯 이번주 디자인 패턴

- 주제 : `옵저버 패턴`
- 미션 : 주식 거래소에서 주식 가격 변동을 관찰하고, 변동이 있을 때마다 해당 주식의 가격 정보를 구독한 사용자들에게 알림을 보내는 프로그램을 작성하세요.
    - 이 미션에서는 **주식 가격 변동**이라는 이벤트가 발생했을 때, 이를 관찰하는 **옵저버들에게 알림을 보내는** 방식으로 옵저버 패턴을 적용할 수 있습니다. 
    - 이를 위해서는 **주식 가격 정보를 저장**하고, 이 **정보가 업데이트될 때마다 옵저버들에게 알림**을 보내는 **중간 관리자 클래스**가 필요합니다. 
    - 이 클래스는 **옵저버들의 목록**을 가지고 있으며, **주식 가격 정보가 업데이트될 때마다** 등록된 **옵저버들에게 알림**을 보내주는 역할을 합니다.

+) JAVA버전 17 통일!

다들 화이팅입니다~!😋🔥🔥

### ✔️ To Do

- [ ] **전날 자정(24:00:00)부터 스터디 전까지** 개인이 만든 코드 PR 보내기, merge는 스터디 모임 때
- [ ] 본인을 제외한 다른 사람이 해당 PR을 제대로 확인하고, 이상 없으면 merge 합니다.

**Comment by namtndus** [comment]
알겠습니다 👍
