### ISSUE TITLE
[2장 네트워크] 회고 (Retrospection)

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#22]
## ✍️ 기억은 기록을 이길 수 없다.

스터디를 시작한 지 3주가 지났네요. 
3주간 함께 공부하면서 혹은 혼자 공부하며 어떤 점을 느끼고 배웠나요. 
스터디에서 건의하고 싶거나 칭찬하고 싶은 이야기 모두 좋습니다.
CS 스터디 관련 내용이 아니더라도 좋아요!
서로에게 힘이 되는 메시지를 주어도 좋아요!

(다 좋아요❣️)

자유롭게 회고 내용을 작성해주세요!

**Comment by namtndus** [comment]
redis에 대해 공부를 했을 때, key-value로 저장이 되어 이것을 어디에 사용하는 것인지 의문을 가졌었는데,스터디를 통해 캐시에 대해 알게 되면서 redis의 필요성에 대해서 알게 되었습니다.
모의 면접을 하면서 정윤님께서 많이 신경써 주셔서 스터디가 원활하게 진행이 되어서 정말 감사합니다. 제가 알고 있다고 생각했는데, 질문을 받으니 머릿속이 새하얏게 되어서 말을 못한게 많이 아쉬웠습니다.

**Comment by ParkJungYoon** [comment]
저는 어제 모의 면접 하면서 오히려 내용을 잘 알수록 장황하게 말할 수도 있다는 것을 알게 되었어요.
물론 추가 질문에 답변하기 위해서 깊게 공부해야 합니다!
대신 앞으로 아는 내용을 듣는 사람이 지루하지 않게 차분하게 말하도록 노력하고 연습을 해야 할 것 같네요!!

**Comment by sanghyuk2** [comment]
문제의 요지를 정확히 파악해야겠다 느꼈습니다. 사람마다 생각하는 바가 다르니 다양한 답변이 나올수 있음은 부정할 수 없는 사실이지만, 현철님의 HTTP 메소드 관련 질문을 받고 질문의 의도를 파악하지 못한채 몇 번 버벅거리고 나니 면접관의 질문의 의도에 맞게 답변을 할 수 있는 능력을 길러야겠다는 생각을 했습니다. 어차피 면접은 상대평가이며, 면접관의 마음에 들어야하는 게임(?)이다보니 풍부한 지식을 가지고 있더라도 의도된 모범 답안에 가깝게 설명을 하지 못하면 의미가 없기에 좀 더 준비를 철저히 해야겠다 느꼈습니다. 또한 아무리 모의면접일지라도 준비를 제대로 해야했으나, 벼락치기식으로 준비를 하다보니 부족함을 많이 보여 지식을 공유해야하는 자리에서 제가 가진 지식을 공유하는 대신 다른 분들의 지식만 가져간 것 같아 본의 아니게 피해를 끼친듯해 죄송스럽네요. 다음 주제 관련 면접 준비 철저히 해서 개선된 모습 보이도록 하겠습니다.

건의하고자 하는 점은, 제가 타자속도가 느려 그런지는 모르겠지만 면접 도중 상대방의 답변을 받아적다보니, 받아적는 도중에 발언된 질문 혹은 새로운 의견 등을 놓쳐 반복해서 되묻는 경우가 종종 생겨 시간의 지연이 생기더라구요. 면접자의 경우 자신이 생각한 답변이 있을 것이고 이에 피면접자가 부합하는 대답만 하면 되기에 답변이 완전히 끝난 뒤 피면접자 피드백(좋았던점/아쉬웠던점/개선점)만 간단히 기록하는 점은 어떨가싶네요. 모의면접시간이 완전히 끝난 뒤 자신의 질문에 면접자가 생각한 답변을 달고, 부족한 지식이 있으면 다른 사람들이 살을 붙이는 형식으로 하면 후에 다시 공부할 때 질문과 답변을 보고 공부하면된다고 생각하는데 다른분들은 어떻게 생각하시나요?

**Comment by baekeunsun** [comment]
**깊이 있게 아는 것이 중요하다고 느꼈습니다.** 면접 준비가 처음이다 보니, 문제은행식 시험에 대처하듯 공부한 것 같습니다. CS 면접 질문들을 검색하여 그 답을 찾으면서 공부하는 방향으로 진행하였습니다. 그렇게 하니 짧은 시간 내에 전체적으로 훑을 수 있다는 장점은 존재하였지만, 준비한 질문이 아닌 다른 질문을 받으면 당황하여 머리가 하얘지는 것을 느꼈습니다. 시간이 없었다는 말은 핑계였음을 자신이 가장 잘 알기 때문에 운영체제에서는 더 많은 시간을 투자하여 겉핥기식 지식이 되지 않도록 하고 싶습니다!


상혁님 말에 공감합니다. 
답변하신 분이 나중에 돌아보기 쉽게 도우려고 답변을 썼는데, 쓰는 사람이 계속 쓰다보니 질문자가 쓰는 사람일 경우 답변을 놓치는 경우가 종종 있었습니다.  

그런데 자신이 잘못된 답변을 했을 때, 무슨 개념과 헷갈리고 있는지 아는 것 또한 중요하다고 생각하기 때문에 답변을 적는 것을 유지하는 것도 좋은 방법같습니다. 
차라리 그 전 질문자가 현재 면접자의 질문을 적고, 면접자는 피드백만 작성하는 것도 괜찮을 것 같습니다.
면접시간이 모두 끝난 후에 면접자가 의도한 방향과 답변이 무엇이였는지, 다른 분들도 추가적인 설명을 덧 붙이는 것은 너무 좋다고  생각합니다!


네트워크 스터디의 경우 처음이라 많이 고쳐나가면서 진행해야할 것이라 생각했는데, 다들 적극적으로 참여하시고 의견 충돌이나 다툼 없이 끝낸 것 같아 기분이 좋네용! 
면접을 죽쒔다고 생각해서 슬펐는데, 다들 좋은 말로 피드백해주셔서 오히려 용기를 많이 얻었습니다. 
운영체제는 더 잘 해보겠습니다!! 같이 힘내봅시다💪💪

**Comment by devFancy** [comment]
본인이 이해한 것을 처음으로 누구에게 설명하듯이 전달하려고 하니, 불필요한 말이 나오거나 정확하지 않게 전달하는 점이 있었습니다.
해당 면접을 준비하기 이전에, 사전에 말하는 연습을 여러번 하면서 최대한 정확하고 듣는이의 귀가 편하게 전달하도록 하겠습니다.

위에서 **상혁**님이 말씀하신 점 `답변이 완전히 끝난 뒤 피면접자 피드백(좋았던점/아쉬웠던점/개선점)만 간단히 기록하는 점` 에 대해서 좋은 지적인 것 같아요! 이 부분에 대해서 **면접 질문에 대한 답변을 전부 적는 것 보다는 간단하게 적는게** 시간 관계상 더 효율적이네요. 굿!입니다~ 👍 

면접 스터디원 모두 열심히 참여해주셔서 정말 감사드리고 앞으로도 꾸준히 화이팅 해봅시다! 😆

**Comment by ParkJungYoon** [comment]
너무 만족합니다. 역시 회고는 필수에요!! 스터디 진행하고 운영하는데 의견과 피드백은 도움이 많이 됩니다!! 
앞서 나온 의견들은 바탕으로 다음주 팀 별 스터디전 한 번 회의하고 시작하도록 하겠습니다! 😉 운영체제도 화이팅 입니다!

**Comment by jthugg** [comment]
공부의 목적과 단계에 대해 다시 생각해보게됐습니다.
우선 공통된 목적으로는 기술면접에서 선방하기위함이고 나아가 직무를 수행하는과정에서 기반지식을 다지기 위함 이라고 생각 합니다.
전반적인 내용을 머릿속에 집어넣는 시기가 있고 반복학습하며 깊이를 늘리는 과정, 그 다음으로는 지식을 바탕으로 타인에게 말로써 전달할 수 있게 정리하는 과정이 있는데 이 과정을 한번에 하려는것 보다는 짧은기간속에서도 시간을 쪼개서 잘 활용하는것이 중요하다고 느꼈습니다.

여러분 덕분에 재밌게 공부 할 수 있었고 앞으로도 더 발전해봐요 파이팅!!👍

**Comment by BHC-Chicken** [comment]
꼬리 질문을 받으면서 아직 부족하다는 것을 많이 느꼈습니다.
말을 할 때도 아직 머릿속으로 정리가 되지 않았는데 일단 말할려고 하다보니 더 꼬인다는 것을 느꼈고, 좀 더 생각을 가다듬고 저의 생각을 깔끔하게 전달하도록 해야겠다고 생각이 들었습니다.

**Comment by ParkJungYoon** [comment]
## `모의면접 진행노트` 작성 관련 피드백 정리

🙋‍♂️ **1. 상혁**
- `답변이 완전히 끝난 뒤` 피면접자 피드백(좋았던점/아쉬웠던점/개선점)만 간단히 기록
- `모의면접시간이 완전히 끝난 뒤` 자신의 질문에 면접자가 생각한 답변을 달고, 부족한 지식이 있으면 다른 사람들이 살을 붙이는 형식

🙋‍♀️ **2. 은선**
- 답변을 적는 것을 유지하는 것도 좋은 방법
- 그 전 질문자가 현재 면접자의 질문을 적고, 면접자는 피드백만 작성
- `면접시간이 모두 끝난 후`에 면접자가 의도한 방향과 답변이 무엇이였는지, 다른 분들도 추가적인 설명을 덧 붙이는 형식

🙋 **3. 팬시**
- `답변이 완전히 끝난 뒤` 피면접자 피드백(좋았던점/아쉬웠던점/개선점)만 간단히 기록
- 면접 질문에 대한 답변을 전부 적는 것 보다는 간단하게 작성

## 종합

**1. 면접 중**
- 그 전 질문자가 현재 면접자의 질문 작성 및 답변 요약해서 작성

**2. 답변 끝난 후**
- 질문자가 피면접자 피드백(좋았던점/아쉬웠던점/개선점) 간단히 기록
- 방향성이 맞았는지 질문자가 간단하게 피드백

**3. 모의면접이 끝난 후**
- 면접자가 의도한 방향과 답변이 무엇이였는지, 다른 분들도 추가적인 설명을 덧 붙이는 형식
