### ISSUE TITLE
[Pended][23년 11월 2주차] 싱글톤 패턴

### ISSUE THREAD

**Issue by jthugg** [Fancy96/2023-CS-study#226]
### 🚀 스터디

- `일시`: 2023-11-22 (수) 20시 ~ 21시 (1h)
- `참석자`:
  - [ ] 5명(네오, 은선, 수연, 현철, 상혁)
- `내용` : 디자인 패턴 이론 공부, 그를 바탕으로 실습 진행

### ✍️ 스터디 방식

1. 책을 통해 이번 주 `디자인 패턴`을 공부한다.
2. 해당 패턴을 이용하여 `미션`을 푼다.
4. 스터디 `전날 12시` ~ `스터디 전` 까지 PR을 날린다.
5.  `코드 리뷰`는 `자율`!

### 🎯 이번주 디자인 패턴

- 주제 : `싱글톤 패턴`
- 미션 : 단단한헬스장
- 전제:
  - 최근 운동을 시작한 `김말랑`은 `단단한헬스장`에 등록했습니다.
  - 헬스장에는 다음과 같은 운동기구가 단 하나씩만 구비돼있고 고유한 번호가 붙어있습니다.
  - 차례로 `1 로잉머신`, `2 스쿼트랙`, `3 트레드밀`, `4 벤치프레스`, `5 렛풀다운`, `6 레그프레스`
  - 현재 헬스장 인원은 `김말랑`포함 4명입니다.
  - 헬스장안에 있는 사람들은 모두 소심한 사람들이라 "몇세트 남았나요?"라는 질문을 못합니다.
- 요구사항:
  - 각 운동기구는 싱글톤 패턴을 사용하여 하나의 인스턴스만 존재하도록 구현되어야 합니다.
  - 각 운동기구는 번호와 사용 가능 여부를 가지고 있어야 합니다.
  - 4명의 인원(스레드)가 헬스장을 이용합니다.
  - 각 인원(스레드)이 생성(초기화)될 때 운동 루틴을 랜덤 숫자열로 생성하고 다음 규칙을 따릅니다.
    - 운동 루틴은 `1 ~ 6` 중 중복없는 5개로 구성됩니다.
    - 단, 모든 스레드가 가지는 운동 루틴의 시작 번호는 중복되면 안됩니다.
    - ex) [1, 2, 3, 4, 5], [1, 3, 2, 4, 5]는 불가능 합니다.
    - [1, 2, 3, 4, 5], [6, 2, 3, 4, 5]는 가능합니다.
    - 점유 시간은 한가지 운동 기구를 점유하는 시간을 나타내며 `1 ~ 10` 중 중복 가능한 5개 숫자로 구성됩니다.
    - 점유시간의 단위는 `초`입니다.
    - 불변필드로 운동 기구 사용 루틴과 점유 시간을 가집니다.
      ```java
      //ex)
      //반드시 배열타입이 아니어도 됩니다.
      //필요하다면 컬렉션을 사용해도 좋습니다.
      ...
      private final int[] machines;
      private final int[] durations;
      ...
      ```
  - 점유하고 있는 기구에서의 운동이 끝나면 비어있는 운동기구로만 이동할 수 있습니다.
  - 만약 비어있지 않다면 빌때까지 현재 운동기구에서 대기합니다.
  - `김말랑`에게 교착상태가 발생하면 `[ERROR] `로 시작하는 메세지를 가진 커스텀 런타임 예외를 발생시키고 종료합니다.
  - `김말랑`이 모든 운동 루틴을 완료했다면 `오운완!`을 출력하고 프로그램을 종료합니다.
  - 다른 인원에게 교착상태가 발생하면 로그를 출력하고 해당 교착상태를 무시하며 진행합니다.
    - 교착상태 로그 양식: `[DEADLOCK] {스레스이름} vs {스레드이름}`
  - 프로그램이 실행되는 동안 각 인원이 점유하고있는 운동기구가 바뀌면 로그를 출력합니다.
    - 로그 양식: `[{스레드이름}] {사용중인운동기구}`
    - 옵저버패턴을 복습하며 구현해주세요.
- 기타 요구사항:
  - Thread safe를 구현하는 문제입니다. `Enum`타입을 허용하지 않습니다.
  - 프로그램 종료 시 `System.exit()`를 호출하지 않습니다.
  - 모든 메서드의 파라미터 개수는 최대 3개까지만 허용합니다.
  - 예외처리 시 `Exception`이나 `RuntimeException`이 아닌 구체적인 예외를 사용하고 처리합니다.
  - Java버전은 17을 사용합니다.

### ✔️ To Do

- **전날 자정(24:00:00)부터 스터디 전까지** 개인이 만든 코드 PR 보내기, merge는 스터디 모임 때
- 본인을 제외한 다른 사람이 해당 PR을 제대로 확인하고, 이상 없으면 merge 합니다.

**Comment by baekeunsun** [comment]
네오..........엄청난 코드 기대합니다......... 내 순서일때 징챠 가만안둬......🥹😭
![image](https://github.com/devSquad-study/2023-CS-Study/assets/72916415/9002ce0c-a62d-47a8-ae60-16abc619ea84)
