### ISSUE TITLE
[3장 운영체제 - 1] 3.1 ~ 3.2까지 내용 학습 및 선택한 주제 공부

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#24]
### 🚀 스터디

- 일시: 2023-01-24 (화) 20시 ~ 22시 (2h)
  - 설연휴에 진행하기 때문에 개인적인 사정이 생길 경우 미리 말씀해주세용!
- PR 마감 날짜: 스터디 전
- 참석자
  - [x] 전원
- 정해야할 내용
  - [x] 실시간 면접 내용 작성 방법 (피드백)
  - [x] 다음 스터디 날짜 조정

### 🎯 공통 주제

- 3.1 운영체제와 컴퓨터
- 3.2 메모리

이 부분은 각자 개인 공부로 진행하시면 됩니다.

### 👩‍💻 개인 주제

- [x] 공부하고 발표하고 싶은 주제를 정해 이슈 답글을 달아주세요!
- [x] 개인 주제를 공부하고 정리해서 스터디 시간에 발표합니다!

### ✔️ To Do

- [x] 스터디 전까지 개인이 정리한 것을 PR 보내기, merge는 스터디 모임 때(이 내용을 토대로 발표)
- [x] 면접 준비(아직 학습 단계이기 때문에 서로 의견 나눌 수 있는 정도로만 준비하시면 됩니다)

**Comment by devFancy** [comment]
저는 `주소 변환`, `세그먼테이션(Segmentation)` 하겠습니다! 😊

**Comment by BHC-Chicken** [comment]
저는 `운영체제와 컴퓨터` 하겠습니다!

**Comment by namtndus** [comment]
저는 `프로세스와 스레드`하겠습니다

**Comment by ParkJungYoon** [comment]
저는 `교착상태(DeadLock)` 준비하겠습니당 😉

**Comment by baekeunsun** [comment]
`CPU 스케줄링 알고리즘` 준비하겠습니다

**Comment by jthugg** [comment]
`가상메모리와 요구페이징, 페이지 교체` 준비하겠습니다

**Comment by sanghyuk2** [comment]
앗 제가 기록을 안남겼었네요. 저는 `인터럽트(Interrupt)`에 대해 준비하겠습니다.
