### ISSUE TITLE
[24년 2월 2주차] 프록시 패턴

### ISSUE THREAD

**Issue by sanghyuk2** [Fancy96/2023-CS-study#257]
### 🚀 스터디

- `일시`: 2024-02-07 (수) 20시 ~ 21시 (1h)
- `참석자`
  - [x] 5명(네오, 은선, 수연, 현철,상혁)
- `내용` : 디자인 패턴 이론 공부, 그를 바탕으로 실습 진행

### ✍️ 스터디 방식

1. 책을 통해 이번 주 `디자인 패턴`을 공부한다.
2. 해당 패턴을 이용하여 `미션`을 푼다.
4. 스터디 `전날 12시` ~ `스터디 전` 까지 PR을 날린다.
5.  `코드 리뷰`는 `자율`!

### 🎯 이번주 디자인 패턴

- 주제1 : `프록시 패턴`
- 미션 : 원격 파일 업로더 시스템을 만들어주세요
- 기능 요구사항 :
1. 원격 파일 업로드 기능:
- 클라이언트는 서버에 파일을 업로드할 수 있어야 합니다.
- 서버는 업로드한 파일을 저장하고 로그에 기록해야 합니다.
2. 메시지 전송 기능:
- 클라이언트는 서버에 메시지를 전송할 수 있어야 합니다.
- 서버는 전송받은 메시지를 출력하고 로그에 기록해야 합니다. 
3. 파일 목록 조회 기능:
- 클라이언트는 서버에 저장된 파일 목록을 조회할 수 있어야 합니다.
- 서버는 파일 목록을 클라이언트에게 반환해야 합니다.

Java RMI를 연습하는 미션입니다.

---
- 주제2 : `프록시 패턴`
- 미션: 권한 부여를 하게 도와주세요
- 시나리오:  

CS Study 회사의 새로운 소프트웨어 개발 프로젝트에서 현재는 모든 팀원이 모든 코드에 대한 액세스 권한을 가지고 있습니다. 그러나 프로젝트 리더인 `네오`가 코드의 보안을 강화하기 위해 각 팀원에게 특정 모듈 또는 기능에 대한 엑세스 권한을 부여하려고 합니다. 예를 들어, CS Study의 구성원은 자신의 직책과 동일한 팀 멤버들의 정보만 확인할 수 있으며, 그 직책보다 상위에 위치한 팀장 네오의 파일에는 열람 권한이 부여되지 않습니다. 

기존 프로그램은 다음과 같이 구성되어 있다고 한다. 먼저 멤버의 직책을 표현하는 ROLE enum 상수 클래스를 정의하였습니다. 아래 코드에서 확인가능하다싶이, 차례대로 사원(Staff), 과장(Manager), 상무(Director) 를 표현하는 상수를 가지고 있습니다.

```
enum ROLE {
    STAFF, // 사원
    MANAGER, // 과장
    DIRECTOR // 상무
}
```

그리고 사람들의 정보를 클래스화한 People 클래스를 정의하였다. 이 클래스에는 구성원의 이름과 직책의 정보를 한번에 알수 있는 getInfo() 메서드를 지원합니다.

```
// 구성원 클래스
class Member {
    private String name; // 이름
    private ROLE position; // 직위

    public Member(String name, ROLE position) {
        this.name = name;
        this.position = position;
    }

    public String getName() {
        return name;
    }

    public ROLE getPosition() {
        return position;
    }

    public String getInfo(Member viewer) {
        return "Display " + getPosition().name() + " '" + getName() + "' personnel information.";
    }
}
```

마지막으로 열람하는 전 구성원을 모두 출력하는 DisplayMemberInfo 클래스 프로그램이 있다. 이 클래스는 생성자의 인자로 누가 조회하는지 대상자(viewer)를 받고 모든 구성원 리스트를 인자로 받아 출력해주는 printAllInfo() 메서드를 지원합니다.

```
class DisplayMemberInfo {
    Member viewer; // 조회하려는 자
    
    DisplayMemberInfo(Member viewer) {
        this.viewer = viewer;
    }
	
    // Member 객체 리스트를 받아 직원들의 정보를 순회하여 조회
    void printAllInfo(List<Member> members) {
        members.stream()
                .map(member-> member.getInfo(viewer))
                .forEach(System.out::println);
    }
}
```

현재 위 코드에선 직책에 따른 클래스 구성 자체에는 문제가 없으나 지금 상태로만 둔다면 **어느 누구든지** DisplayMemberInfo 객체를 통해 printAllInfo() 메서드를 실행시켜 모든 사람들의 리스트를  볼 수 있습니다.

```
public static void main(String[] args) {
    // 직원별 개인 객체 생성
    Member CTO = new Member ("NEO", ROLE.DIRECTOR);
    Member devManager = new Member ("상혁", ROLE.MANAGER);
    Member financeManager = new Member ("은선", ROLE.MANAGER);
    Member devStaff = new Member ("현철", ROLE.STAFF);
    Member financeStaff = new Member ("수연", ROLE.STAFF);

    // 사람들을 리스트로 가공
    List<Member> Member = Arrays.asList(CTO, devManager, financeManager, devStaff, financeStaff);

    // 나 : 일개 멤버 직책
    Member me = new Member("ME", ROLE.STAFF);

    System.out.println("\n================================================================");
    System.out.println("일개 멤버인 내가 회사에선 열람 최강자..?");
    System.out.println("================================================================");
    DisplayMemberInfo view = new DisplayMemberInfo(me); // 모든 사람들 정보를 출력하는 클래스
    view.printAllInfo(members); // 일개 멤버에 불구하고 모든 사람들 조회
}
```

**출력물**
```
================================================================
일개 멤버인 내가 회사에선 열람 최강자..?
================================================================
Display DIRECTOR 'NEO' personal Information
...
```

### 원하는 미션 선택해서 풀어주세요~~

+) JAVA버전 17 통일!

다들 화이팅입니다~!😋🔥🔥

### ✔️ To Do

- [x] **전날 자정(24:00:00)부터 스터디 전까지** 개인이 만든 코드 PR 보내기, merge는 스터디 모임 때
- [x] 본인을 제외한 다른 사람이 해당 PR을 제대로 확인하고, 이상 없으면 merge 합니다.

**Comment by namtndus** [comment]
교수님 오늘 문제에 힘을 주셨군요 ㅎㅎㅎ 열심히 해오겠습니다😀
