### ISSUE TITLE
[2장 네트워크 - 1] 2.1 ~ 2.2까지 내용 학습 및 정리

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#3]
### 🚀 스터디

- 일시: 2023-01-03 (화) 20시 ~ 22시 (2h)
- PR 마감 날짜: 2023-01-02 (월)
- 참석자
  - [x] 전원

### 🎯 주제

- 2.1 네트워크의 기초 
- 2.2 TCP/IP 4계층 모델 

팀 내에서 주제는 겹칠 수 있습니다. 각자 원하는 주제를 선택한 후 이름을 작성해주세요.

### ✔️ To Do

- [x] 월요일 자정까지 개인이 정리한 것을 PR 보내기(이 내용을 토대로 발표하셔도 좋습니다)
- [x] 면접 준비(아직 학습 단계이기 때문에 서로 의견 나눌 수 있는 정도로만 준비하시면 됩니다)

**Comment by ParkJungYoon** [comment]
### 🐰 A팀

- 네트워크의 기초(상혁)
- TCP/IP 4계층 모델 (팬시, 수연)

### 🐤 B팀

- 네트워크의 기초 (현철)
- TCP/IP 4계층 모델 (은선, 주디)

**Comment by ParkJungYoon** [comment]
`TCP/IP 4계층` `애플리케이션 계층` 내용에서 DNS가 보여서 네트워크에서 중요한 포인트 중 하나인 **웹 전반적인 통신 흐름**에 대해서 정리하겠습니다.

**Comment by baekeunsun** [comment]
`TCP/IP 4계층` `전송 계층` 에서 **TCP와 UDP의 차이**와 **TCP의 연결 및 해제 과정**에 대하여 정리하겠습니다!

**Comment by sanghyuk2** [comment]
'네트워크 기초'

**Comment by sanghyuk2** [comment]
`네트워크의 기초` 섹션 중 **2.1.2 네트워크 토폴로지와 병목 현상** 정리하겠습니다.

**Comment by jthugg** [comment]
`네트워크 기초` 파트 에서 `대역폭`을 상세히 다뤄보겠습니다.
파트정리 이해를 잘못해서 늦어져서 죄송해요,, ;_;
