### ISSUE TITLE
[3장 운영체제 - 2] 3.3 ~ 3.4까지 내용 학습 및 선택한 주제 공부

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#35]
### 🚀 스터디

- 일시: 2023-02-02 (목) 20시 ~ 22시 (2h)
- PR 마감 날짜: 스터디 전
- 참석자
  - [x] 전원

### 🎯 공통 주제

- 3.3 프로세스와 스레드
- 3.4 CPU 스케줄링 알고리즘

이 부분은 각자 개인 공부로 진행하시면 됩니다.

### 👩‍💻 개인 주제

- [x] 공부하고 발표하고 싶은 주제를 정해 이슈 답글을 달아주세요!
- [x] 개인 주제를 공부하고 정리해서 스터디 시간에 발표합니다!

### ✔️ To Do

- [x] 스터디 전까지 개인이 정리한 것을 PR 보내기, merge는 스터디 모임 때(이 내용을 토대로 발표)
- [x] 면접 준비(아직 학습 단계이기 때문에 서로 의견 나눌 수 있는 정도로만 준비하시면 됩니다)

**Comment by namtndus** [comment]
저는 `PCB와 Context Switching`를 할게요

**Comment by devFancy** [comment]
저는 `페이징(Paging)` 하겠습니다.

**Comment by ParkJungYoon** [comment]
저는 `동기화(스핀락, 뮤텍스, 세마포어)` 준비해오겠습니당 🤭

**Comment by sanghyuk2** [comment]
`시스템 콜` 준비해볼게요 :-)

**Comment by baekeunsun** [comment]
저는 `메모리` 준비해오겠습니다~

**Comment by jthugg** [comment]
`TLB` 준비하겠습니다.

**Comment by BHC-Chicken** [comment]
`멀티프로세스, 멀티스레딩` 준비하겠습니다.
