### ISSUE TITLE
[3장 운영체제 - 3] 모의 면접

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#42]
### 🚀 스터디

- 일시: 2023-02-07 (화) 20시 ~ 22시 (2h)
- PR 마감 날짜: 스터디 전
- 참석자
  - [x] 팬시, 해시, 네오, 은선, 수연
  - [x] 부상자: 상혁 노트북, 주디 몸
- 내용
  - 모의 면접 (면접 내용 공유)
  - 질문 md 파일 하나에 통합
  - 다음 데이터베이스 팀 정하기
  - 데이터베이스 공부 분량 정하기
 
### 🎯 공통 주제
- 운영체제 전체

### ✔️ To Do
 - [x] 스터디 전까지 운영체제 전반적으로 공부하기 
 - [x] 각자 정리한 내용 공부하면서 모르는 부분 질문하기
 - [x] 면접 준비

크 드디어 운영체제도 끝나가네요!! 파이팅!!!

**Comment by ParkJungYoon** [comment]
### ✔️ 공지

> PR 마감 날짜 변경
  - **월요일 자정**
  - **추가 commit은 허용한다.**

**Comment by ParkJungYoon** [comment]
## ✔️ 진행 방식
- [면접 노트](https://docs.google.com/document/d/1QnsMgR9M0c91QetYJPhUuUABAFgMVCrpuYvNV04bXjQ/edit)

### 1. 면접 중
- 전전 출제자가 현재 면접자의 **질문 작성 및 답변**을 요약해서 작성한다.
- 예) 출제자 `1. 주디 2. 은선 3. 네오 4. 현철 5. 네오 6. 상혁 7. 팬시` 순서로 진행할 때
        `주디`부터 시작하면, 전전 출제자인 `상혁`이 질문 작성 및 답변을 요약해서 작성한다.


### 2. 답변 끝난 후
- 출제자가 피면접자 **피드백**(좋았던점/아쉬웠던점/개선점) 간단히 기록한다.
- 방향성이 맞았는지 출제자가 간단하게 피드백을 작성한다.



### 3. 모의면접이 끝난 후
- 면접자가 의도한 방향과 답변이 무엇이였는지, 다른 분들도 추가적인 설명을 덧 붙이는 형식

**Comment by Fancy96** [comment]
### 📝 질문 리스트 docs

- 10일 자정까지 각자 준비한 질문들 올려주세요!
- 그리고 network 폴더에 md 파일로 만들어서 README.md에 추가합시다!
- [질문 리스트](https://docs.google.com/document/d/11K4btdrkJtTWlA4LClFTIycmlnO7KWOtFEdYVUn3P-Y/edit)
