### ISSUE TITLE
[3장 운영체제] 회고 (Retrospection)

### ISSUE THREAD

**Issue by devFancy** [Fancy96/2023-CS-study#50]
## ✍️ 기억은 기록을 이길 수 없다.

여러분 벌써 스터디를 시작한 지 6주가 지났습니다..! (시간 정말 빠르네요..ㅎㅎ)

3주간 함께 운영체제 공부하면서 혹은 다른 CS 공부하며 어떤 점을 느끼고 배웠을까요?
스터디에서 **건의**하고 싶거나 **칭찬**하고 싶은 이야기 모두 좋습니다.

CS 스터디 관련 내용이 아니더라도 좋습니다!
서로에게 힘이 되는 메시지를 주어도 좋습니다!

(다 좋아요❣️)

편하실 때 자유롭게 **회고 내용**을 작성해주세요~
(3주간 운영체제 공부하시고 모의면접 준비하시느라 다들 고생많으셨습니다 😌👍)

**Comment by devFancy** [comment]
### Title : OS.. 너를 완벽하게 이해하긴 어려워도 많은 것을 학습하게 해줘서 참으로 고맙다🤣

_**난이도 : 운영체제 > 네트워크**_
운영체제 과목은 내용이 풍부했고, 이해의 수준이 높아서 네트워크보다 공부 시간이 더 오래 걸렸던 것 같습니다.
그만큼 운영체제 다양한 개념들과 예시, 심화 자료를 학습하면서 많은 것을 배웠습니다.

_**학습한 것을 공유하기**_
제가 배운 내용을 팀원들에게 쉽게 이해시키기 위해서 많은 참고서와 말하는 연습을 하면서, 
첫 번째 회고 때의 '저'보다 조금 더 성장했다는 것을 느꼈습니다.

**_모의면접 : 다음엔 pass를 하지말자_**
모의면접을 진행하면서 운영체제를 이전에 공부해왔던 '저'로써 참으로 부끄럽고 민망했습니다.
**동기화**와 **페이징 교체 알고리즘**에 대한 질문이 들어왔을 때, 아무런 대답을 못해서 결국 `pass`를 하게 되었습니다.
이 부분에 대해서는 이후에 개별적으로 공부해서 보완해나가겠습니다.
다음번엔 **'내가 공부한 개념뿐만 아니라, 남들이 알려준 개념들도 내것으로 만들자.'**

**Comment by namtndus** [comment]
<h3>배우는 것 :  깊은 지식이 잠들어 있다😥</h3>
책으로 읽었을 때는 다 이해했다고 생각을 하였지만, 스터디원들의 내용을 공부하다보니, 아직 배워야 할 것이 많은데, 책의 내용이 전부인 양 생각 한 것 같아, 부끄럽다는 생각이 들었습니다. 운영체제를 깊게 들어가니 이해가 안되는 부분도 많아서 난이도가 상당하다고 느꼈습니다.

<h3>기록 : 앞으로 읽은 사람을 고려하겠습니다!!!!!🤩  </h3>
정보 전달을 위해 다른 블로그 글과 홈페이지 내용을 요약하는 것에만 초점을 맞추어서 글을 작성하였지만, 주디님의 글에는 읽은 이가 이해하기 쉽게 예제를 상세히 적어 놓으셔서 이해를 하는 데에 많은 도움이 되었습니다. 저도 앞으로 독자님을 생각햐면 글을 써야 겠다 생각했습니다

<h3>모의 면접: 면접자 질문자 모두 중요해!!!</h3>
배운 내용이 이해를 했지만, 머릿속에서 정리가 안되서, 공부를 하는데에 초점이 맞추어있었다. 면접질문에 대한 준비를 소흘히 해서 면접자분들에게 죄송합니다! 꼬리 질문애 관한 질문을 더 찾아와야 겠다는 생각이 들었다. 
질문을 받고 바로 대답을 하여 대답하는 와중에 질문을 잊어버리는 상황이 발생한다. 말의 끝맺음을 횡설수설하게 된다. 질문을 받고 5초 정도를 생각하는 시간을 가져야 겠다는 생각이 들었다. 그리고 그 이상이 걸리면 양해를 구한 후 머릿속에 정리하고 대답하도록 노력하자

**Comment by ParkJungYoon** [comment]
### 1. 감사합니다.

많이 응원해주셔서 감사합니다!!! 응원과 격려는 박고래를 춤추게 했어요~~ 덩실덩실

### 2. 칭찬합니다.

정리해주신 내용 모두 깊이 있고 이해하기 편하게 작성되었어요.
이렇게 하나씩 지식을 쌓아나가면 저희도 멋진 개발자가 될 수 있으리라 생각해요!! 하팅

그리고 저번주 라이센스도 추가하고 브랜치 전략도 세워준 팬시도 고생했고 감사합니당!! 

### 3. 의견있어요.

운영체제..너란 친구.. 넓고 어려운 과목이었어요.
3주 만에 모든 파트? 저는 그저 눈물만 나옵니다.
특히 가상메모리 파트를 많이 공부하지 못해서 아쉬움이 있어요.
데이터베이스 끝나고 보강 기간을 가져도 좋을거같아요!! 운체 조금 더 공부하고 싶은 욕심이 있네용!!

p.s 운체 회고에 소제목이 대세인 듯 하여 대세를 따라보았습니다. 😏😘

**Comment by baekeunsun** [comment]
### 네트워크라는 산을 넘었더니 더 큰 운영체제.. 🤦‍♀️
#### 이해하기 쉬운 글이 더 오래 기억에 남는다.
이번 주 MVP를 뽑으라면 **주디** 인것 같아요! 얼마나 깔끔하고 이해하기 쉽던지,, 
또한, 관련 질문을 심화내용으로 해놓으면 더 제대로 공부할 수 있을 것이라 생각했는데, 해당 글을 한번 더 점검하는 느낌의 질문도 도움이 되는 것을 느꼈습니다.

#### 질문을 잘 하는 것도 실력이다.
**팬시**와 **네오**의 페이지 테이블 저장위치에 대한 질문과 대답을 하는 장면(?)이 인상깊었습니다.
저라면 제가 공부한 파트와 다른 부분이 나왔을 때, 그렇게 질문을 못할 것 같았거든요.
내가 잘못봤나? 이런생각으로 혼자 조용히 공부를 더 하고 질문을 했을 것 같아요. 자신이 공부한 내용에 자신있었던 팬시와 마찬가지로 자신있게 술술 대답할 수 있는 네오를 보면서 적어도 제 파트만큼은 그 정도 할 수 있어야겠다 싶었습니다!

#### 반성합니다.
가상메모리 파트는 팬시의 열렬 지도로 꽤 자신있다고 생각했는데, 네오가 내신 페이지 파트 질문에 대답을 하나도 못하는 제가 미웠습니다..🥺 다음주에는 적어도 대답은 할 수 있게! 제대로! 꼼꼼히! 공부해오겠습니다.

그리고 보강 기간 좋아요!

**Comment by jthugg** [comment]
#### 반성합니다.

 모의면접 중 질문을 하려는 찰나 '아, 뭘 질문해야하지?' 라는 생각이 들어 어떤 질문이 좋은 질문 인가에 대해 고민해보는 계기가 되었습니다. 마치 '사람은 왜 사람인가요?'라는 질문 처럼 뚜렷하지 않고 영양가 없는 질문을 반복하는것 같아 죄책감이 들었습니다.

 여러분 그리고 나 스스로에게 도움이 되는 질문을 할 수 있도록 더 노력하겠습니다.
