### ISSUE TITLE
[4장 데이터베이스 - 1] 4.1 ~ 4.3 내용 학습 및 선택한 주제 공부

### ISSUE THREAD

**Issue by devFancy** [Fancy96/2023-CS-study#54]
### 🚀 스터디

- 일시: 2023-02-14 (화) 20시 ~ 22시 (2h)
- PR 마감 날짜: 13일 (월) 자정까지
- 참석자
  - [x] 5명(팬시, 주디, 네오, 상혁, 현철)
- 비참석자
  - [x] 수연(자격증 시험)
  - [x] 은선(몸살)
 - 영광의 첫 벌칙
   -  수연(PR 과제 미제출자)
   -  네오(지각)
- 정해야할 내용
  - [x] 다음 모의면접 혹은 1주 연장할지 결정

### 🎯 공통 주제

- 4.1 데이터베이스의 기본
- 4.2 ERD와 정규화 과정
- 4.3 트랜잭션과 무결성

이 부분은 **각자 개인 공부로 진행**하시면 됩니다.

### 👩‍💻 개인 주제

```markdown
## 목차

* [x] Key(기본키, 후보키, 슈퍼키 등등)

* [ ] ERD와 정규화 과정

* [x] 트랜잭션(ACID 원칙)

* [x] 트랜잭션 격리 레벨

* [x] RDB와 NoSQL

* [ ] 인덱스

* [ ] 조인

* [ ] 저장 프로시저

* [ ] Schema

## 심화 버전

* [x] RDB와 NoSQL에서의 클러스터링/레플리케이션 방식

* [x] B-Tree와 B+Tree

* [ ] MySQL Architecture

* [ ] DB Locking

* [ ] DB의 Connection Pool

* [ ] Trigger

* [ ] Redis
```
- [x] 공부하고 발표하고 싶은 주제를 정해 이슈 답글을 달아주세요!
- [x] 개인 주제를 공부하고 정리해서 스터디 시간에 발표합니다!

### ✔️ To Do

- [x] **전날 자정(24:00:00)까지** 개인이 정리한 것을 PR 보내기, merge는 스터디 모임 때(이 내용을 토대로 발표)
- [x] 본인을 제외한 다른 사람이 해당 PR을 제대로 확인하고, 이상 없으면 merge 합니다. 
- [x] 면접 준비(아직 학습 단계이기 때문에 서로 의견 나눌 수 있는 정도로만 준비하시면 됩니다)

**Comment by devFancy** [comment]
저는 `RDB와 NoSQL` 하겠습니다.

**Comment by ParkJungYoon** [comment]
저는 `트랜잭션`과 `Isolation level` 같이 준비해볼게용~

**Comment by BHC-Chicken** [comment]
저는 `B-Tree와 B+Tree` 준비하겠습니다.

**Comment by jthugg** [comment]
`Key` 준비하겠습니다.

**Comment by namtndus** [comment]
`트랜잭션` 준비해 올게요!

**Comment by baekeunsun** [comment]
`RDB와 NoSQL에서의 클러스터링/레플리케이션 방식` 하겠습니다!

**Comment by sanghyuk2** [comment]
`ERD와 정규화 과정` 담당하겠습니다.
