### ISSUE TITLE
[README.md] 문제제기 : PR 수 & Merge Conflict

### ISSUE THREAD

**Issue by devFancy** [Fancy96/2023-CS-study#58]
🧐**문제 제기**

* 기존에 `README.md` 파일에서 수정이 필요한 경우 브랜치`readme-patch` 에서 수정하고 PR를 보내서 Merge하고 있습니다.
* 하지만 팀원들마다 `README.md`를 매번 로컬 브랜치에서 PR를 보내서 Merge를 함으로써 **무분별한 PR 수를 늘려서 비효율적인 상황**이 발생하고 있습니다.
* 그리고  같은 branch인 `readme-patch`에서 동일한 파일에 수정을 하는 경우 **Merge Confilct**이 발생할 수 있습니다. 

* 해당 부분을 개선하기 위해 몇 가지 **건의 사항**을 전달합니다.

📋**건의 사항**

1. `README.md`에 대해 수정 사항이 있는 경우, issues number를 포함해서 브랜치를 만든다. 
(단 **폴더명**은 readme 기존대로 유지한다. 예) issues number = 60인 경우 -> 브랜치 이름 : `readme/60`
-> 이렇게 하면 팀원 모두 `README.md` 수정은 가능하고 Merge Conflict이 해결되지만, **비효율적인 상황에 대한 문제는 해결되지 않습니다**.

2.  `README.md`에 대해 수정 사항이 있는 경우, `README.md` 파일을 관리하는 사람에게 해당 수정 된 부분을 정리해서 전달한다.
-> 이렇게 하면 비효율적인 상황과 Merge Conflict은 해결되지만, **관리자를 제외한 나머지 팀원은 PR를 보낼 순 없게 됩니다.**

3. 번외로) `README.md`에 대한 수정 사항이 자주 생길 수 있기 때문에, 1~2주에 한 번 Merge하는 것도 좋을 것 같습니다.

혹시나 이것보다 더 **좋은 방안**이 있거나 **다른 의견**이 있으시다면 말씀해주시면 감사하겠습니다.☺️

**Comment by ParkJungYoon** [comment]
### 🙋‍♀️ 주디

Repository 가장 메인의 README.md에 대한 수정은 사실 대부분의 규칙이 정해진 지금. 잦은 변경이 없을 것으로 판단돼요.
자잘한 규칙 수정이나 log 추가 등은 있을 수 있지만 변경이 시급하지 않기 때문에 한 번에 수정 후 머지하는 것이 좋아 보이네요.

현재 팀 레포를 사용하지 않고, 각자 fork한 레포를 사용하는 시점에서 가장 좋은 방법은 README.md는 한 명이 수정하는 것이라고 생각해용!
이슈를 하나 열고 필요한 수정 사항을 기록해 둔 다음 3번 의견대로 1~2주에 한 번 머지 하도록 합시다!!

그리고 추가로 팬시는 현재 자신의 계정 repo에서 작업하기 때문에 feature 브랜치를 생성해서 PR 올리고 있습니다. 해당 내용에 대한 수정과 작업이 끝났다면 머지 시 작업한 feature 브랜치 정리도 해주시면 좋을 거 같아요! (앗! 생각해보니 작업하면서 필요해서 남겨둘 수도 있겠네요!!! 이 점은 고려 안해도 될거같아요!!)

**Comment by baekeunsun** [comment]
### 🙋‍♀️ 은선

제 생각에는 `README.md`를 여러명이 관리하기보단 한 명이 수정하는 게 가장 좋은 방법 같습니다.

주디가 제안한 것처럼 이슈를 하나 열어, 기간을 정해서 수정 사항을 한번에 머지하는 방법이 제일 좋은것 같아요!

**Comment by devFancy** [comment]
그러면 **주디**님이 `README.md`를 관리하는 것으로 정리하겠습니다!
업데이트 기간은 매주이고, 시간은 회의 끝나는 이후로 할게요!
