### ISSUE TITLE
[4장 데이터베이스 - 2] 4.4 ~ 4.7 내용 학습 및 선택한 주제 공부

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#68]
### 🚀 스터디

- 일시: 2023-02-21 (화) 20시 ~ 22시 (2h)
- PR 마감 날짜: 13일 (월) 자정까지
- 참석자
  - [x] 7명(팬시, 주디, 네오, 상혁, 현철, 은선, 수연)

### 🎯 공통 주제

- 4.4 데이터베이스의 종류
- 4.5 인덱스
- 4.6 조인의 종류
- 4.7 조인의 원리

이 부분은 **각자 개인 공부로 진행**하시면 됩니다.

### 👩‍💻 개인 주제

```markdown
## 목차

* [x] Key(기본키, 후보키, 슈퍼키 등등)

* [x] ERD와 정규화 과정

* [x] 트랜잭션(ACID 원칙)

* [x] 트랜잭션 격리 레벨

* [x] RDB와 NoSQL

* [x] 인덱스

* [x] 조인

* [x] 저장 프로시저

* [x] Schema

## 심화 버전

* [x] RDB와 NoSQL에서의 클러스터링/레플리케이션 방식

* [x] B-Tree와 B+Tree

* [x] DB Locking

* [x] DB의 Connection Pool

* [x] Trigger

* [x] Redis
```
- [x] 공부하고 발표하고 싶은 주제를 정해 이슈 답글을 달아주세요!
- [x] 개인 주제를 공부하고 정리해서 스터디 시간에 발표합니다!

### ✔️ To Do

- [x] **전날 자정(24:00:00)까지** 개인이 정리한 것을 PR 보내기, merge는 스터디 모임 때(이 내용을 토대로 발표)
- [x] 본인을 제외한 다른 사람이 해당 PR을 제대로 확인하고, 이상 없으면 merge 합니다. 
- [x] 면접 준비(아직 학습 단계이기 때문에 서로 의견 나눌 수 있는 정도로만 준비하시면 됩니다)

**Comment by ParkJungYoon** [comment]
`인덱스` 준비하겠습니다.

**Comment by BHC-Chicken** [comment]
`Redis` 준비하겠습니다.

**Comment by jthugg** [comment]
`조인` 준비하겠습니다.

**Comment by devFancy** [comment]
`DB Locking` 준비하겠습니다.

**Comment by sanghyuk2** [comment]
`DB의 Connection Pool` 도전해보겠습니다.

**Comment by namtndus** [comment]
`트리거` 준비하겠습니다

**Comment by baekeunsun** [comment]
`저장 프로시저` 하겠습니다!

**Comment by devFancy** [comment]
나머지 `Schema`는 제가 다음주 내로 추가로 업로드하겠습니다.

**Comment by ParkJungYoon** [comment]
드디어 데이터베이스 개념 끄읏~!!
