### ISSUE TITLE
[모의 면접] 면접 기준 설정

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#92]
### 기존 방식 문제점

어떤 점이 부족한지 한 눈에 피드백을 받기 어렵다.

### 개선된 방식 아이디어

점수로 평가하자. 
1~5로 나누어 평가합니다. 각각의 단계에 기준에 대한 의견을 자유롭게 말해주세요!

**Comment by ParkJungYoon** [comment]
5: 개념을 깊이 있게 알고 있으며, 말로 전달할 수 있음.
4: 개념을 깊이 있게 알고 있지만, 말로 전달하는데 미숙함.
3: 개념을 어느 정도 이해하고 있으며, 말로 전달할 수 있음.
2: 개념을 어느 정도 이해하고 있지만, 말로 전달하는데 미숙함.
1: 개념에 관한 공부가 필요함.

**Comment by devFancy** [comment]
5단계로 나누어 평가하는 것도 나쁘지 않는데, 조금 더 단순 명료하게 **4단계**로 하는건 어떤가요? 🤔
저는 다음과 같이 정리해봤습니다.

1. 개념을 이해하고 공부해야할 필요가 있음. (지식 부족)
2. 개념을 어느 정도 이해하지만, 깊이 있게 이해하지 못함. (깊이 있는 지식 부족)
3. 개념을 깊이 있게 이해하고 있지만, 상대방에게 말로 전달하는데 **미숙함**. (전달력 부족)
4. 개념을 깊이 있게 이해하고 있으며, 상대방에게 **쉽고 정확하게** 전달할 수 있음.

**Comment by jthugg** [comment]
반대되는 의견이긴 한데 개인적으론 항목을 세부적으로 나눴으면 좋겠어요.
저는 이렇게 정리 해 봤습니당,, 너무 세부적으로 점수를 나누진 않고 중요한 것들만 추가해봤습니당

예)
**질문 Qn: blah blah**

커뮤니케이션
- 질문자의 의도 파악: 1~5점
- 답변 전달력: 1~5점

지식
- 질문 관련 지식 이해: 1~5점

**Comment by baekeunsun** [comment]
사실 저도 팬시랑 주디 의견을 보고 차라리 `개념`과 `전달력` 두가지로 나누어서 평가하는게 낫지 않나 생각했어요.
너무 세분화되나 해서 말았는데, 네오 의견 나온김에 말해봅니다🙋‍♀️

`커뮤니케이션`, `지식`으로 나누어서 점수 매기는거 받고, 매기는 항목이 세분화됐으니 점수는

1. 부족
2. 보통
3. 만족

이정도로만 나누어도 괜찮을 것 같습니다.

**Comment by ParkJungYoon** [comment]
왕 인성 검사 하는 기분이에요(?) 
의견 다 너무 좋아요!!! 굿굿🙆‍♀️

**Comment by devFancy** [comment]
네오님, 은선님 의견을 반영해서 추가적으로 덧붙이자면, 
질문대로 점수를 매기기 이전에, 질문 및 피드백 작성하는 것도 있기 때문에 **시간이 지체**될 수도 있다고 생각합니다.

그래서 보통 한사람당 한 주제에 대해 2가지씩 질문을 하기 때문에, **주제**를 기준으로 `커뮤니케이션`, `지식`으로 점수 매기면 좋을 것 같아요!

### [예시]

#### 주제 : 그래프(완전탐색, 이진탐색)

- 커뮤니케이션 : 2점
- 지식 : 3점

[키워드] - 네오님 의견 반영
[점수] - 은선님 의견 반영
