### ISSUE TITLE
[4장 데이터베이스] 회고 (Retrospection)

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#93]
## ✍️ 기억은 기록을 이길 수 없다.

달리다보니 데이터베이스까지 끝났네요!!! 2달동안 고생 많았어요!!
이제 새로운 3월 시작! 자료구조도 힘내봐용!

오늘도 스터디를 통해 배우고 느낀 점을 함께 공유해요!❣️

현재 진행 중인 건의사항도 만관부!
추가 건의사항이 있다면 댓글 달아주세요!!

**Comment by ParkJungYoon** [comment]
## 좋은 개발자가 되려면 존재하는 기술을 적재적소에 사용할 수 있어야 한다.

확실히 데이터베이스가 백엔드 CS의 꽃🌷이었어요! 
데이터베이스 파트를 공부하며 `좋은 개발자가 되려면 존재하는 기술을 적재적소에 사용할 수 있어야 한다`는 것을 깨달았어요. 그래야 좋은 설계를 할 수 있고 그런 개발자가 되기 위한 기본이 CS 공부였어요!

저는 야생마 주디로(?) 냅다 개발을 시작했어요! 그리고 CS 공부를 하면서 지난 프로젝트를 많이 되돌아보고 다시 공부하는 계기가 되었습니다.
제가 맡았던 인덱스, 트랜잭션은 실무 개발과 밀접한 개념이었어요!

과거 인덱스와 트랜잭션을 적용했던 서비스를 보며 
"아..! 그래서 인덱스를 걸어도 조회 성능이 향상되지 않았구나!"를 깨닫기도 했고, "아 여기서는 트랜잭션을 거는 게 의미가 없구나!" 라는 것을 깨닫기도 했어요!
이제 알아요!! `트랜잭션은 트랜잭션이 필요한 기능 범위에만 최소한으로 적용해야 한다.`

이번 정리 덕분에 포폴과 이력서도 한 번 더 검토하게 되었습니다!! **따봉 스터디**🤍
지난 제가 했던 개발을 되돌아보니 정말 아무것도 모르던 시절에서 많이 발전해서 신기하네요!
요즘 매주 코테로 기가 빨리고 자소서 쓴다고 개발과 잠시 멀어지고 있지만 이 과정이 지나고 다시 개발자로 성장하는 기회를 가지면 좋겠습니다!! 
(악 저녁에 또 코테야 엉엉 개발이 최고 재밌어 ㅠㅠ 자소서, 코테 시렁..)
모두 실무에서 만나 다음 스터디(?)를 도모하는 그날까지 포기하지 않고 함께 힘내요!!
정말 저의 원동력은 함께 공부하는 거 같아요!!! ㅠ_ㅠ 함께 해주는 개발자들이 없었다면 금방 지쳤을 거예요 ㅠㅠ 
(아침부터 갬성 주디, 모닝 스타벅스가 이렇게 위험합니다.)

\+ 추가로 아이고.. 취준한다고 개발에 손을 좀 뗐더니 고새 다 까먹고 있는 거 같아요 ㅋㅋㅋㅋㅋㅋ 제가 했던 프로젝트, 열심히 포스팅과 포폴로 정리했던 부분도 대답을 어버버했네요!
👍**따봉네오**👍 덕분에 예전 코드, 글 다시 확인하면서 redis, refresh token 이제 대답할 수 있어요!!! 하하하 나중에 다시 질문해주세요 ㅎㅅㅎ

그럼...20000..주디 빵 먹으러 갑니다 냠냠🥯

**Comment by baekeunsun** [comment]
### 아쉬움이 남는 데이터 베이스 😔
#### 스터디의 순기능😆💜
감기 몸살, 시험 때문에 데이터 베이스는 한번밖에 참여하지 못 했네요..😥
한번 뿐이였지만, **상혁님의 교수님 급 설명**과 여태 배운 내용이 어우러져서 굉장히 의미있던 시간이었습니다.

확실히 스터디했던 내용을 기반으로 새로운 내용을 이해할 수 있을 때 더 재밌는것 같아요!
TCP나올때 그렇게 반갑더라고요?ㅋㅋㅋ
또한 저장프로시저 설명할 때에 주디가 예전에 가졌던 의문을 해결하는 것을 보고 뿌듯했습니다. 

#### 데이터 베이스 앵콜부탁해요ㅜㅜㅠㅠ
백엔드와 데이터베이스는 뗄래야 뗄 수 없는 사이 아니겠습니까
다른 분들이 정리해준 데이터베이스 파트 열심히 공부해서 중간중간 질문하겠습니다!
3주간 수고하셨고, 자료구조 화이팅해용

이때를 틈타  `10cm -  뗄래야 뗄 수 없는 사이` 추천합니다 🤭

**Comment by jthugg** [comment]
## 여러분 고마워요 😁
지난해 국비과정을 거쳐서 DB를 처음 접하게 됐는데 이번 주제 공부하면서 많은것들이 제대로 머리에 각인된 계기가 됐습니다.
공부해온 과정을들 돌아보며 아, 여기선 어떤 문제가 있겠구나 하며 또 한번 공부하게 됐습니다.

야생마 **주디** 꼬리에 꼬리를 무는 질문 릴레이에 깜짝 놀랐던 모의면접이었습니다 덕분에 하드트레이닝을 받은 기분이에요 ㅋㅋㅋ
어떻게 좋은 질문들만 골라서 해주시는지,,, 팁이 있다면 배워가고싶어요
그리고 스터디 지휘자 **팬시**! 항상 생각하는거지만 **팬시**가 사소한것 부터 하나하나 잘 조율해주고 좋은 의견들은 내 줘서 많은것들을 배워가요!!

**Comment by namtndus** [comment]
### 데이터베이스를 얕보았다.

DB를 배우면서 DB의 모든것은 DDL, DML, DCL 이라고 생각했습니다.
이번에 배우면서, 더 깊은 내용을 가지고 있었습니다. 
그 정보를 공부를 하는데 머리에 들어온다는 느낌이 들지 않았습니다. 
왜 이해를 못하지, 어느 부분이 어려운 거지? 라면서 현타도 많이 왔습니다. 
면접에 대답을 많이 못해서 많이 아쉽웠습니다
다시 데이터베이스에 공부를 해야 겠다는 다짐이 들었습니다

면접 질문에 다른 분들의 꼬리 질문을 어떻게 그렇게 잘 하시는지 정말 감탄하면서 참가를 했습니다. 
모의 면접에 참여 해주신 주디님, 네오님,. 팬시님. 상혁님, 은선님, 현철님 감사합니다

**Comment by sanghyuk2** [comment]
### **공부의 길은 끝이 없다..!**

데이터베이스 파트를 공부하며 지금까지 개발의 의미를 모르며 프로그래밍을 해왔구나를 실감했습니다.
그렇기에 프로그래밍 공부를 할 때 내가 왜 공부 속도가 느린지에 대하여 알게됐습니다.
강의 및 관련 서적들을 통하여  부분부분 공부를 하다보니 사용법을 단순 암기식으로 습득하였지만 큰 흐름을 파악하지 못한채 넘어가니 나중에 개발에 접목시키려 하니 어려움이 많더군요. 
개인적으로 생각하는 백엔드 개발자로써 가장 중요한 지식은 `어떻게 하면 데이터를 보다 효율적으로 관리할 수 있을까`라고 생각하는데 그에 해답을 주는 한 주였던것 같습니다. 또한 제가 CS관련 지식 중 가장 흥미를 가장 가졌던 파트이기에 시간가는줄 모르고 공부했습니다.
여러분들의 관련 포스팅을 하나하나 읽으면서, 또 발표 시간을 거치면서 내가 조사해왔던 지식들이 여러분들 포스팅에 올라오는걸 보며 반가움을 느끼는 시간도 가졌어요!
물론 단순히 글만 읽고 이해하기 어려운 부분도 여럿 있었으나 여러분들의 친절한 답변을 통하여 깨달음을 얻을 수 있는 좋은 시간이었습니다.
