### ISSUE TITLE
[5장 자료구조 - 1] 5.1 ~ 5.3 내용 학습 및 선택한 주제 공부

### ISSUE THREAD

**Issue by ParkJungYoon** [Fancy96/2023-CS-study#95]
### 🚀 스터디

- 일시: 2023-03-08 (수) 20시 ~ 22시 (2h)
- PR 마감 날짜: 7일 (화) 자정까지
- 참석자
  - [x] 5명(주디, 네오, 상혁, 은선, 수연)
  - [x] 현철, 팬시 개인사정
  - 팬시 경고!

### 🎯 공통 주제

- 5.1 복잡도
- 5.2 선형 자료 구조
- 5.3 비선형 자료 구조

이 부분은 **각자 개인 공부로 진행**하시면 됩니다.

### 👩‍💻 개인 주제

```markdown
## 목차

* [ ] 시간복잡도와 공간복잡도

* [x] 스택과 큐

* [x] 링크드 리스트

* [x] 트리

* [x] 이진탐색트리(레드블랙트리)

* [ ] 그래프

* [x] 힙

* [x] 정렬

* [x] 해시

* [ ] 이진탐색

* [ ] 완전탐색

* [ ] B-Tree & B+Tree

* [ ] 그리디 알고리즘

* [x] 암호화 알고리즘
```
- [x] 공부하고 발표하고 싶은 주제를 정해 이슈 답글을 달아주세요!
- [x] 개인 주제를 공부하고 정리해서 스터디 시간에 발표합니다!

### ✔️ To Do

- [x] **전날 자정(24:00:00)까지** 개인이 정리한 것을 PR 보내기, merge는 스터디 모임 때(이 내용을 토대로 발표)
- [x] 본인을 제외한 다른 사람이 해당 PR을 제대로 확인하고, 이상 없으면 merge 합니다. 
- [x] 면접 준비(아직 학습 단계이기 때문에 서로 의견 나눌 수 있는 정도로만 준비하시면 됩니다)

**Comment by devFancy** [comment]
저는 `링크드 리스트` 와 `트리` 하겠습니다~

**Comment by ParkJungYoon** [comment]
저는 `이진탐색트리(레드블랙트리)` 준비하겠습니당!

**Comment by namtndus** [comment]
저는 `정렬`를 하겠습니다

**Comment by jthugg** [comment]
`스택과 큐` 준비하겠습니다!

**Comment by BHC-Chicken** [comment]
`해시` 준비하겠습니다.

**Comment by baekeunsun** [comment]
`암호화 알고리즘` 준비하겠습니다~

**Comment by ParkJungYoon** [comment]
우왕 암호화 알고리즘 궁금해요!!!! 은선님 마지막에 발표해주세요(?) 일찍 끝나고 도강하게..🫣

**Comment by sanghyuk2** [comment]
`힙` 준비하겠습니다!!
